### ISSUE TITLE
fix examples on 2.2.0

### ISSUE THREAD

**Issue by gcb** [dropbox/dropbox-sdk-python#1]
is this the official place for the SDK i can download on dropbox.com?

this seems outdated. i wanted to patch the examples to work with python3 as they are failing currently because of syntax errors.

**Comment by smarx** [comment]
This is the repo for the new Python SDK being built to support API v2. See https://blogs.dropbox.com/developers/2015/06/preview-python-sdk-for-api-v2/.

The source code for the v1 SDK is available for download at https://www.dropbox.com/developers/core/sdks/python. That SDK doesn't currently support Python 3.
