### ISSUE TITLE
the users_get_current_account throwing random errors

### ISSUE THREAD

**Issue by lernerc** [dropbox/dropbox-sdk-python#100]
I had my setting for my token wrong and got a very weird error and it is not the one listed in /example/back-up-and-restore/backup-and-restore-example.py
With one strange token I got 
BadInputError: BadInputError('9a64573c9c6137aee07442aeb73fe6c2', u'Error in call to API function "users/get_current_account": The given OAuth 2 access token is malformed.')
InternalServerError: InternalServerError('ef5833b349d652ebd7677170f334fbab', 500, u'')
and those passed back values are not the tokens I passed in.
The first one was a valid token that I just removed the last 40 characters or so, and the other one was from a bunch of random characters and letters passed in.

**Comment by greg-db** [comment]
The `BadInputError` is expected if the access token doesn't match the expected access token format. You'd only get an `AuthError` if the token looked possibly valid, but wasn't actually valid on the server (e.g., if it was a real access token, but was revoked).

Can you share the code to reproduce the 500 error though? Thanks in advance!

**Comment by lernerc** [comment]
```
    dbx = dropbox.Dropbox(TOKEN) # a valid token with the last 40 characters removed
    try:
        dbx.users_get_current_account()
    except dropbox.exceptions.AuthError as err:
        raise StandardError("ERROR: Invalid access token; try re-generating an access token from "
                            "the app console on the web.")```

**Comment by greg-db** [comment]
Thanks! We'll look into it.

**Comment by jamescooke** [comment]
My test suite accidentally sent some test values to the Dropbox API via the Python SDK and I ran into the same unexpected `InternalServerError`. The strange thing is that this happened for one value and not the others, so I can reproduce with an exact string:

    from dropbox import Dropbox
    Dropbox('__NOT_EVEN_LIKE_A_TOKEN__').users_get_current_account()
    ...
    BadInputError: BadInputError('c5e8f9a15877e5114d7c89917a53b2d0', 'Error in call to API function "users/get_current_account": The given OAuth 2 access token is malformed.')   # As expected
    # but...
    Dropbox('__APP_GENERATED_TOKEN__').users_get_current_account()
    ...
    InternalServerError: InternalServerError('a75144999252ac6798972306a0c60dca', 500, '')

Hope that's helpful.

**Comment by greg-db** [comment]
Thanks for the sample!

**Comment by greg-db** [comment]
Apologies for not following up on this sooner. This was fixed a little while back.
