### ISSUE TITLE
Upload Folders

### ISSUE THREAD

**Issue by EsterfanoLopes** [dropbox/dropbox-sdk-python#107]
I'm not finding how to upload folders. Is it there?
Maybe i have to use the same method to file upload?

> files_upload(f, path, mode=WriteMode('add', None), autorename=False, client_modified=None, mute=False)
> Create a new file with the contents provided in the request. Do not use this to upload a file larger than 150 MB. Instead, create an upload session with files_upload_session_start().
> 
> Parameters:	
> f (bytes) – Contents to upload.
> path (str) – Path in the user’s Dropbox to save the file.
> mode (dropbox.files.WriteMode) – Selects what to do if the file already exists.
> autorename (bool) – If there’s a conflict, as determined by mode, have the Dropbox server try to autorename the file to avoid conflict.
> client_modified (Nullable) – The value to store as the client_modified timestamp. Dropbox automatically records the time at which the file was written to the Dropbox servers. It can also record an additional timestamp, provided by Dropbox desktop clients, mobile clients, and API apps of when the file was actually created or modified.
> mute (bool) – Normally, users are made aware of any file modifications in their Dropbox account via notifications in the client software. If True, this tells the clients that this modification shouldn’t result in a user notification.
> Return type:	
> dropbox.files.FileMetadata
> 
> Raises:	
> dropbox.exceptions.ApiError
> 
> If this raises, ApiError.reason is of type:
> dropbox.files.UploadError

My idea is to upload the whole folder, instead of uploading file by file. How you people do that?

**Comment by greg-db** [comment]
@BarbaL The SDK doesn't offer the ability to upload entire folders at once. You'll need to upload each file as necessary. We'll consider it a feature request though.

**Comment by BarbaL** [comment]
@greg-db Thank you for the quick answer. I'll think in someway to loop on files into folder. I'll keep watching this topic also.

And if i can help anyway, let me know.

**Comment by Anmar-Salih** [comment]
Hey,
Here is an example to upload the entire folder.

 
`import dropbox, sys, os

dbx = dropbox.Dropbox(' YOUR KEY')
rootdirx = "/home/anmar/Desktop" 



print ("Attempting to upload...")

for dir, dirs, files in os.walk(rootdirx):
    for file in files:
        try:
            file_path = os.path.join(dir, file)
            dest_path = os.path.join('/test', file)
            print 'Uploading %s to %s' %  (file_path, dest_path)
            with open(file_path) as f:
	     	
              dbx.files_upload(f.read(), dest_path, mute=True)
        except Exception as err:
           print("Failed to upload %s\n%s" % (file, err))
	   

print("Finished upload.")`

Hope this will help.

**Comment by rogebrd** [comment]
Closing due to a found resolution.

**Comment by KyluAce** [comment]
This solution doesn't work if in main folder exist some subfolders.
