### ISSUE TITLE
Get metadata of doc in Paper?

### ISSUE THREAD

**Issue by demon386** [dropbox/dropbox-sdk-python#108]
ListPaperDocs only returns Doc ids. How can I get metadata like modification time with SDK?

**Comment by greg-db** [comment]
You can use [`paper_docs_download`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.paper_docs_download) to get [some metadata, like `owner`, `title`, and `revision`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.paper.PaperDocExportResult), but the API doesn't currently expose modification time. We'll consider it a feature request.

**Comment by rogebrd** [comment]
Unfortunately, this issue is out of the hands of the team handling the SDKs and we will not be fixing this due to how stale the issue is.  If this is still needed, please reopen this issue and we can reach out to the team who owns this and try to get this added.
