### ISSUE TITLE
Error importing dropbox 

### ISSUE THREAD

**Issue by erikskou** [dropbox/dropbox-sdk-python#112]
After installing the "dropbox SDK" on my RaspberryPi

    pi@raspberrypi:~ $ sudo pip install dropbox
    Downloading/unpacking dropbox
      Downloading dropbox-7.3.1-py2-none-any.whl (416kB): 416kB downloaded
    Downloading/unpacking requests>=2.5.1,!=2.6.1 (from dropbox)
      Downloading requests-2.18.1-py2.py3-none-any.whl (88kB): 88kB downloaded
    Requirement already satisfied (use --upgrade to upgrade): urllib3 in /usr/lib/python2.7/dist-packages (from dropbox)
    Requirement already satisfied (use --upgrade to upgrade): six>=1.3.0 in /usr/lib/python2.7/dist-packages (from dropbox)
    Downloading/unpacking certifi>=2017.4.17 (from requests>=2.5.1,!=2.6.1->dropbox)
      Downloading certifi-2017.4.17-py2.py3-none-any.whl (375kB): 375kB downloaded
    Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests>=2.5.1,!=2.6.1->dropbox)
      Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
    Downloading/unpacking idna>=2.5,<2.6 (from requests>=2.5.1,!=2.6.1->dropbox)
      Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
    Installing collected packages: dropbox, requests, certifi, chardet, idna
      Found existing installation: requests 2.4.3
        Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
      Found existing installation: chardet 2.3.0
        Not uninstalling chardet at /usr/lib/python2.7/dist-packages, owned by OS
    Successfully installed dropbox requests certifi chardet idna
    Cleaning up...

I get this error when "data_logger.py" try to import dropbox

    pi@raspberrypi:~/cb_logging/bin $ sudo ./data_logger.py
    /usr/local/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.9.1) or chardet (3.0.4) doesn't match a supported version!
      RequestsDependencyWarning)
    Traceback (most recent call last):
      File "./data_logger.py", line 17, in <module>
        import dropbox
      File "/usr/local/lib/python2.7/dist-packages/dropbox/__init__.py", line 3, in <module>
        from .dropbox import __version__, Dropbox, DropboxTeam, create_session  # noqa: F401
      File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 18, in <module>
        import requests
      File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 90, in <module>
        from urllib3.exceptions import DependencyWarning
    ImportError: cannot import name DependencyWarning
    pi@raspberrypi:~/cb_logging/bin $

Any ideas?

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://stackoverflow.com/questions/44675934/python-2-7-import-dropbox-sdk-error](https://stackoverflow.com/questions/44675934/python-2-7-import-dropbox-sdk-error) ]

The [requests library requires](https://github.com/requests/requests/blob/56971482af7ff5d2b0ea9b0908eb90a1369b57a3/setup.py#L47) 
```
'urllib3>=1.21.1,<1.22',
```

You apparently have `urllib3==1.9.1` installed though, which isn't in that supported range, so you should upgrade `urllib`, e.g., with:

```
pip install urllib3 --upgrade
```

**Comment by erikskou** [comment]
Hi. Thank for the help.
But when I try to upgrade it says that I have the latest version. And at the same time that it is ver. 1.9.1-3

I have also tried to remove the module and reinstall. But still ver. 1.9.1-3

    pi@raspberrypi:~ $ sudo apt-get install python-urllib3 --upgrade
    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    python-urllib3 is already the newest version.
    0 upgraded, 0 newly installed, 0 to remove and 303 not upgraded.
    pi@raspberrypi:~ $ dpkg -s python-urllib3
    Package: python-urllib3
    Status: install ok installed
    Priority: optional
    Section: python
    Installed-Size: 239
    Maintainer: Debian Python Modules Team <python-modules-team@lists.alioth.debian.org>
    Architecture: all
    Version: 1.9.1-3
    Depends: python:any (<< 2.8), python:any (>= 2.7.5-5~), python-six
    Recommends: ca-certificates, python-ndg-httpsclient, python-openssl, python-pyasn1
    Description: HTTP library with thread-safe connection pooling for Python
     urllib3 supports features left out of urllib and urllib2 libraries.
     .
       - Re-use the same socket connection for multiple requests (HTTPConnectionPool
         and HTTPSConnectionPool) (with optional client-side certificate
         verification).
       - File posting (encode_multipart_formdata).
       - Built-in redirection and retries (optional).
       - Supports gzip and deflate decoding.
       - Thread-safe and sanity-safe.
       - Small and easy to understand codebase perfect for extending and
         building upon.
    Homepage: http://urllib3.readthedocs.org
    pi@raspberrypi:~ $

**Comment by greg-db** [comment]
It looks like you're using `apt-get` to install `urllib3`. Perhaps your apt cache is out of date? Try updating it (`apt-get update`) and then upgrading `urllib3` again.

Also, I believe that may not be necessary anyway. You could also try uninstalling that `urllib3` and just letting `pip install dropbox` install all of the dependencies, including `urllib3` for you.

**Comment by erikskou** [comment]
Hi
It still not work. I have now changed my project so I upload my data to a database instead of Dropbox, so I don't need to upgrade urllib3. But thanks for the input.

**Comment by Sphinxs** [comment]
Some update ?

```
➜  markov git:(master) ✗ pip freeze | grep urllib3
urllib3==1.23
➜  markov git:(master) ✗ python3 enem.py
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
➜  markov git:(master) ✗
```

**Comment by greg-db** [comment]
@Sphinxs That appears to be correct, as [the requests library, as of the latest release, still requires](https://github.com/requests/requests/blob/a3d7cf3f27e74c28ef30f01e9f2e483570ab042e/setup.py#L47)

    'urllib3>=1.21.1,<1.23',

You have 1.23 installed, which isn't in that range. You'll need to install a supported version.

(It looks like the requests library code was [recently updated to allow 1.23](https://github.com/requests/requests/commit/ac944b7439009ffbf7a10dfee35202f1ac090e76#diff-2eeaed663bd0d25b7e608891384b7298), but that's not released yet.)

**Comment by Sphinxs** [comment]
@greg-db Thanks, `sudo pip install 'urllib3<1.23'`
