### ISSUE TITLE
dropbox.stone_validators.ValidationError

### ISSUE THREAD

**Issue by Casyfill** [dropbox/dropbox-sdk-python#118]
my code keeps raising the ValidationError, even for the trivial paths / filenames:

dropbox.stone_validators.ValidationError: 'PriceAndRentAndQuintilesIndices.csv' did not match pattern '(/(.|[\r\n])*)|(ns:[0-9]+(/.*)?)'

here is a snippet of code I have:

```
client = dropbox.Dropbox(DB['token'])
path = 'PriceAndRentAndQuintilesIndices.csv'

with io.StringIO() as f:
            DF.to_csv(f, index=None)
            self.client.files_upload(f=f, path=path, mode='overwrite')
```

**Comment by Casyfill** [comment]
oh I see,  it requires slash in the beginning of the path. 
it would be great to have this note in the documentation or raised Error.

**Comment by greg-db** [comment]
Thanks for the feedback! I'm glad to hear you sorted this out already. That's correct, when specifying a file's path, it must start with a `/`.

**Comment by fabswt** [comment]
Still would make sense to provide a more sensible error message (for missing slash.)

**Comment by greg-db** [comment]
Thanks for the additional feedback! I'll make a note of this with the team.

**Comment by ijunaid8989** [comment]
I am passing  a slash such as

I got this error

```
:python, :"dropbox.stone_validators.ValidationError", '\'b\'/Construction2/gpocam/5919/2020-05-12T11:00:01Z.jpg\'\' expected to be a string, got bytes', ['  File "/usr/local/lib/python3.6/dist-packages/dropbox/stone_validators.py", line 303, in validate\n    % (val, generic_type_name(val)))\n', '  File "/usr/local/lib/python3.6/dist-packages/dropbox/files.py", line 484, in path\n    val = self._path_validator.validate(val)\n', '  File "/usr/local/lib/python3.6/dist-packages/dropbox/files.py", line 456, in __init__\n    self.path = path\n', '  File "/usr/local/lib/python3.6/dist-packages/dropbox/
```
