### ISSUE TITLE
check if object is file or folder (help needed)

### ISSUE THREAD

**Issue by carlottanegri** [dropbox/dropbox-sdk-python#120]
how do I check if an object is a folder or a file in v2? 
my dirty workaround is to look at 
`hasattr(dbx.files_get_metadata(path),'media_info')` where 
`dbx = dropbox.Dropbox(drpbx_acces_token)`, 
which is True if file and False if folder, 
but that must be a dedicated tag somewhere..

**Comment by greg-db** [comment]
You can use `isinstance` to check the type, `FileMetadata`, `FolderMetadata`, or `DeletedMetadata`, as shown here:

https://github.com/dropbox/dropbox-sdk-python/blob/cb149fafeedf08a6a0456219518aafda3a1fa3ca/example/updown.py#L91

**Comment by carlottanegri** [comment]
that's what I needed, thanks a lot!
