### ISSUE TITLE
how to check for existence of a file?

### ISSUE THREAD

**Issue by oohh270** [dropbox/dropbox-sdk-python#121]
Hi,
Im trying to find a way how to check for existence of a file in dropbox.
I need something like 

if file is exist in my dropbox:
    do something
else
    do something else

how can I do it?
Thanks!

(I dont know how to insert the code here..)

**Comment by deathnfudge** [comment]
You can use files_get_metadata(). 
[http://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_get_metadata](url)

If the file exists, it will return the metadata of the file. If it doesn't, it will raise an api exception. There are multiple exceptions, so you can tell if it doesn't exist or if it was deleted etc. You can handle the exception and do whatever you need to do at that point.

**Comment by greg-db** [comment]
That's correct, thanks!
