### ISSUE TITLE
Cant use dropbox on raspberry pi

### ISSUE THREAD

**Issue by oohh270** [dropbox/dropbox-sdk-python#123]
Hi,
Im trying to run my python app on my raspberry pi. On the pc it run fine, but on the pi I have an error "no module named dropbox".
I installed it on the pi (pip install dropbox) and still have the same problem...

**Comment by oohh270** [comment]
?

**Comment by posita** [comment]
I'm not that familiar with Raspberry Pi, nor is not something Dropbox tests with regularly, and there's very little information in your original post to guess at what's going on here. Perhaps you can help troubleshoot this a bit further? For example:

1. How was `pip` installed?
1. Did `pip install dropbox` succeed or were there any error messages?
1. Are you using `pip` for a different version of Python than your run-time version?
1. Where does `pip` install its packages on Raspberry Pi?
1. Is that location in your Python's `sys.path` by default?
1. Do other packages work when installed via `pip`?

Based on your original post, it sounds like this is a problem with your Python environment, not the Dropbox SDK. I'm closing this for now, but please feel free to reopen if you are able to gather more information that points to an SDK failure.

**Comment by oohh270** [comment]
Hi,
1) I wrote "pip install dropbox" and "sudo pip install dropbox". 
2) with sudo and wothout sudo it was success (and now when im trying to install it again i have a message that it already installed)
3) I dont understand your question. I have python 3 and this is the version of python that I write with.
4-5) I dont know... :(
6) how can I check? Which package I can try for it?

Thank you...
