### ISSUE TITLE
Requests 2.14.2 not compatible?

### ISSUE THREAD

**Issue by anishathalye** [dropbox/dropbox-sdk-python#124]
I maintain git-remote-dropbox, a package that depends on this SDK. Some people have pointed to an issue they believe is caused by dropbox-sdk-python not being compatible with Requests 2.14.2 (see https://github.com/anishathalye/git-remote-dropbox/issues/65#issuecomment-323613456), and that this could be resolved by requiring `requests >= 2.18.1`.

Is this a change you could make here? (that would be much nicer than working around this issue)

**Comment by greg-db** [comment]
Thanks! Yes, there was an issue with some versions of the requests library. I'll ask the team to update the requirements on the Dropbox library accordingly.

**Comment by littleninja** [comment]
Duplicate of #114?

**Comment by anishathalye** [comment]
Yeah, looks like that's the same thing. Any chance it'll be fixed soon, or should I work around it?

**Comment by greg-db** [comment]
That's correct Sarah, that appears to be a duplicate. I'm closing this in favor of that one. Thanks!

@anishathalye I don't have a timeline right now, so if this is blocking you, you may want to workaround it on your side for now. Apologies for the trouble!

**Comment by greg-db** [comment]
We've updated the dependencies in [v8.4.0](https://github.com/dropbox/dropbox-sdk-python/releases/tag/v8.4.0).
