### ISSUE TITLE
Did not match pattern

### ISSUE THREAD

**Issue by andreyshedko** [dropbox/dropbox-sdk-python#126]
I'm using DropboxApi V.2 with Python 3.6. When I'm trying to upload file, I'm getting error `did not match pattern '(/(.|[\r\n])*)|(ns:[0-9]+(/.*)?)|(id:.*)`
Meanwhile, the string `/agromash/uploading/somefile.json` perfectly valid for the regex mentioned above. What is wrong here?
```python
    def start_uploading(self, fileName):
      try:
        dbx = dropbox.Dropbox('token')
        full_path = '/agromash/uploading/' + fileName[fileName.rfind('/') + 1:]
        print(full_path)
        with open(fileName) as f:
            dbx.files_upload(self, f.read(), full_path)
            self.statusBar().showMessage('Файл загружен:' + dbx.files_get_metadata(full_path))
     except Exception as inst:
            print(type(inst))
            print(inst.args)
            print(inst) 
```

**Comment by greg-db** [comment]
Hi Andrey, it looks like you're passing in `self` as the first parameter to [`files_upload`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload), and `f.read()` as the second parameter. The first and second parameter should be the file content and the path though. That is, you're actually passing in the file content as the path. Try just removing `self` from that call and let us know if it doesn't help:

```
dbx.files_upload(f.read(), full_path)
```

**Comment by andreyshedko** [comment]
Thanks!
