### ISSUE TITLE
Make the process of getting entry type for `files_list_folder` more obvious

### ISSUE THREAD

**Issue by tivaliy** [dropbox/dropbox-sdk-python#128]
Now, if we want to get to know whether the entity fetched from `files_list_folder` belongs to files or folders we have to do the following steps:

```python
dbx = ......
response = dbx.files_list_folder(source)
    for entry in response.entries:
        if isinstance(entry, FileMetadata):
            print('{} is of file type'.format(entry.name))
```

Maybe it's worth to add some kind of attribute to `Metadata` class that will definitely identify entity type. I think this make the process of fetching entity type more obvious?

**Comment by greg-db** [comment]
Thanks for the feedback!

**Comment by mtruong-dbx** [comment]
This issue is very old and we are not going to prioritize it due to the lack of interest over the years.
