### ISSUE TITLE
files_list_folder (recursive=True) returns only 2000 entities of all the files stored

### ISSUE THREAD

**Issue by uzwatcher** [dropbox/dropbox-sdk-python#136]
Hello!
Using this code, it returns only first 2000 entities (Both folders+images).
However, I have more. Why don't I receive the rest?

import dropbox
dbx = dropbox.Dropbox('<TOKEN>')
for e in dbx.files_list_folder('/extended-cohn-kanade-images/cohn-kanade-images', recursive=True).entries:
    print (e.name)
    i += 1
    print(i)

**Comment by greg-db** [comment]
The `list_folder` results are paginated, so there is a limit to how many to be returned per page.
 [The `files_list_folder` method](ListFolderResult) returns a [`ListFolderResult`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.files.ListFolderResult) object. If [`ListFolderResult.has_more`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.files.ListFolderResult.has_more) is `True`, you need to call back to [`files_list_folder_continue`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_list_folder_continue) to retrieve more results (and so on).

There's more information about this in [the `files_list_folder` documentation](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_list_folder).

**Comment by uzwatcher** [comment]
Thanks, it works
