### ISSUE TITLE
Organize the documentation

### ISSUE THREAD

**Issue by ewjoachim** [dropbox/dropbox-sdk-python#14]
Hello, 

I was invited by [Steeve Marx](https://twitter.com/smarx/status/641384219349024769) to create issues for my remarks on the API, so here it is.

For now, your documentation is really hard to grasp. I can really see that it's just the output of Sphinx' Autodoc, but it could help if there was an **introduction**, some **documented examples** on most of the methods on the Dropbox object etc. It took me some time to figure out that all I ever have to instantiate was a Dropbox object. Lots and lots of classes listed here are for "internal" use only (for example, the *Args).

**Comment by smarx** [comment]
Have you seen https://www.dropbox.com/developers/core/start/python (or the v2 equivalent https://www.dropbox.com/developers-preview/documentation/python#tutorial)? If so, does that help?

This may be clearer once we release v2 and the /developers-preview becomes /developers. Then developers will presumably see the documentation and tutorials there.

**Comment by braincore** [comment]
@ewjoachim We're definitely planning to write an introduction for the SDK in the sphinx docs similar to [what Steve linked](https://www.dropbox.com/developers-preview/documentation/python#tutorial). Pure auto docs aren't any fun. I'll update this when they're there.

Filtering out the internal-only classes is also in the works.

**Comment by ewjoachim** [comment]
Nope, didn't see that, and not very sure how I would have, as far as I could see, there's no link to either from github or from Read the Docs, is it ?

So, yeah, it helps.

By the way, at this point, you probably have figured that I'm always complaning so it will not be a surprise if I say the following :D

If you add parenthesis in your prints (in the samples on that page), it will be valid for python 2 AND 3. Now it's just valid for python 2.

Thank you !

--
 Joachim Jablon

**Comment by ewjoachim** [comment]
I think what's unclear is the state of this project. What still needs to be done, what is considered final, what are you expecting feedback on. Otherwise, most of what we'll say will be things you already knew and aready planned...

**Comment by braincore** [comment]
@amfelds It doesn't look like we advertise your new `back-up-and-restore` example in the repo README or on our Python tutorial page. Could you help with this?

**Comment by rogebrd** [comment]
We have since added a [CONTRIBUTING.rst](https://github.com/dropbox/dropbox-sdk-python/blob/master/CONTRIBUTING.rst) which outlines basic guidelines.  Our [README.rst](https://github.com/dropbox/dropbox-sdk-python/blob/master/README.rst) now contains both examples and links to the code.
