### ISSUE TITLE
AttributeError: module 'dropbox' has no attribute 'Dropbox'

### ISSUE THREAD

**Issue by danteay** [dropbox/dropbox-sdk-python#141]
I follow the documentation of your SDK but in the first step the module can't access to Dropbex object and the console show the nex error:

```
Traceback (most recent call last):
  File "dropbox.py", line 1, in <module>
    import dropbox
  File "/Users/danteay/Desktop/apps/ms-comreport/dropbox.py", line 3, in <module>
    dbx = dropbox.Dropbox('xxxx')
AttributeError: module 'dropbox' has no attribute 'Dropbox'
```

I use python 3.6.4.

**Comment by braincore** [comment]
You'll need to rename your Python file from `dropbox.py` to something else like `myapp.py`. It's an unfortunate issue related to Python's package/module resolution system.

**Comment by sawrupesh04** [comment]
I think your py file is dropbox.py were you writing your code  C
#!dropbbox.py
import dropbox
dropbox.Dropbox('token')
#this will give you error

Change your python file and then try.
