### ISSUE TITLE
team_log_get_events_continue() not paging properly

### ISSUE THREAD

**Issue by elreydetoda** [dropbox/dropbox-sdk-python#143]
Greetings,

I have successfully gotten the first 1000 events by doing the `dropbox.Dropbox(apiKey).team_log_get_events()` command. After that though I create a variable for the cursor and then call the `team_log_get_events_continue(events.cursor)`, but when I get the events returned from the `team_log_get_events_continue()` it is still the same 1000 events...

here is my code just to make sure that I am doing it right, I have added in the `print('1')` and `print('2')` because that I wanted to differentiate when it gets returned. Also I am printing out the cursor just to make sure it is changing (which it is). Also I know I can set the `dropbox.Dropbox(apiKey)` to a variable, but I am just sending it in full length because I am making sure nothing is residual in variables causing the error I am having.

```
from csv import reader
import dropbox, json, time

with open('/path/to/file/with/apiKey') as csvfile:
    readz = reader(csvfile, delimiter=':')
    for row in readz:
        if row[0] == 'dropbox':
            apiKey = row[2]

events = dropbox.Dropbox(apiKey).team_log_get_events()

for i in events.events:
    print(i.timestamp)

print('1')
print(events.cursor)

newevents = dropbox.Dropbox(apiKey).team_log_get_events_continue(events.cursor)


for i in newevents.events:
    print(i.timestamp)

print('2')
print(newevents.cursor)
```

is there something I am doing wrong to not get the next set of data? The printing of the cursors show that they are different, so I should be getting the next set of data right?

**Comment by greg-db** [comment]
Thanks for the report! This looks like a bug on our side. We're looking into it.

**Comment by elreydetoda** [comment]
Awesome, thanks @greg-db

**Comment by elreydetoda** [comment]
Any progress @greg-db ?

**Comment by greg-db** [comment]
No, I don't have an update on this yet. I'll follow up here once I do.

**Comment by greg-db** [comment]
Apologies for the delay. This is still open with the team, but we don't have a fix for it yet.

As a workaround though, this issue shouldn't occur if you pass any parameters to the initial `team_log_get_events` call.

**Comment by greg-db** [comment]
This should be working as expected now.
