### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by rianhunter** [dropbox/dropbox-sdk-python#156]
In https://github.com/rianhunter/dbxfs/blob/master/setup.py#L40 I don't specify an upper bound for the version of the Dropbox SDK but under a semantic versioning scheme I should. Upping major version numbers is a signal that the new version of the library isn't backwards compatible with the the previous version, yet Dropbox Python SDK bumps major versions regularly. Can we make sure the version numbers follow a semantic versioning scheme for those packages that rely on this package?

**Comment by greg-db** [comment]
Yes, we do already follow semantic versioning for the SDKs. If you see us make a mistake and ship a breaking change without a major version number increase, please let me know.

**Comment by rianhunter** [comment]
The problem I observed in the past is that you bump major version numbers without breaking compatibility, not that you break compatibility without bumping the major version number. Admittedly this is not a strict violation of semantic versioning, which only states you **must** bump the major version if breaking changes have occurred, not that you **must not** bump the major version if breaking changes have not occurred. For this packages specifically, have other factors, aside from breaking compatibility, contributed to the decision of bumping the version number?

**Comment by greg-db** [comment]
I see, thanks for clarifying. I'd have to double check with the team, but I believe the expectation is that we'd only bump the major version for breaking changes. 

Is there a specific release you're thinking of that you can point to as an example? That would be helpful to review with the team. Thanks!

**Comment by greg-db** [comment]
Thanks, that makes sense. The SDKs contain a lot of different functionality nowadays, so it's definitely likely any one app may not be affected by whatever breaking changes are introduced with any particular major release.

I believe we do already keep old versions up though, e.g.: https://pypi.org/project/dropbox/3.42/ .

**Comment by rianhunter** [comment]
Wow, noted, okay sorry for this. I must be misremembering exactly what caused the dropbox dependency to fail then.
