### ISSUE TITLE
How to delete a file from dropbox?

### ISSUE THREAD

**Issue by wassimgoodar** [dropbox/dropbox-sdk-python#159]
Hi I wanted to overwrite a file in dropbox(that is i have an image and i want to overwite it with another image with the same name)

is that possible??
I want to do this programatically using python and dropbox APi2

**Comment by greg-db** [comment]
It sounds like you actually are asking two different questions here:

> How to delete a file from dropbox?

To delete a file using the Dropbox API from the Dropbox Python SDK, you would use [the `files_delete_v2` method](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_delete_v2).

> I wanted to overwrite a file in dropbox(that is i have an image and i want to overwite it with another image with the same name)

You can overwrite an existing file, without deleting it first, by using [the `files_upload` method](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload) (or [`files_upload_session_finish`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_upload_session_finish), if using upload sessions) with a `mode` of [`WriteMode.update`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.files.WriteMode.update) (preferred) or [`WriteMode.overwrite`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.files.WriteMode.overwrite).
