### ISSUE TITLE
Add suppport for http proxy connections

### ISSUE THREAD

**Issue by dfranganillo** [dropbox/dropbox-sdk-python#16]
Given that requests is used to handle the http magic, It'll be nice to expose the proxies parameter in order to support http/s proxies.

**Comment by braincore** [comment]
Thanks for the report! Is this urgent? We'll address it with a release within 2 weeks.

For now, you can set the `HTTP_PROXY` and/or `HTTPS_PROXY` environment variables as detailed here: http://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by dfranganillo** [comment]
Does it work with Core V1? I tried it before and it does not seem so.

**Comment by braincore** [comment]
This has been resolved in version 3.32. You can now pass a `proxies` argument when instantiating the `Dropbox` class. You can see the documentation here: http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.dropbox.Dropbox.__init__
