### ISSUE TITLE
I get windows local path instead of dropbox link

### ISSUE THREAD

**Issue by AliPolat** [dropbox/dropbox-sdk-python#165]
Help please :

I am desperate and find this place to get help ...

I get this error when I try to access dropbox files:

Exception Type: | ValidationError
'D:/home/site/wwwroot/media/urunler/Koala.jpg' did not match pattern '(/(.|[\r\n])|id:.)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'

My development environment :
python 3.6
django 2.1
django-storages 
dropbox-sdk

I get this error when I use windows,  with linux no problem arises.

I discussed this issue with the guys at django-storages side and they routed me here..

Is this an issue of dropbox-sdk ?

**Comment by greg-db** [comment]
This error is indicating that the `path` value you're supplying to the Dropbox API call is not a valid Dropbox path.

You're supplying the value `'D:/home/site/wwwroot/media/urunler/Koala.jpg'`, but that's a local filesystem path, not a path in the Dropbox format. A path for the Dropbox API should be relative to the Dropbox folder, and should look something like `"/SomeFolder/file.ext"`. I.e., it shouldn't have a drive value like "D:".

You can build these values yourself, or you can get valid Dropbox paths from elsewhere on the Dropbox API itself. For instance, you can get Dropbox paths for other files or folders from [the `Metadata.path_lower` field](https://dropbox-sdk-python.readthedocs.io/en/latest/api/files.html#dropbox.files.Metadata.path_lower), e.g., as found in the result of [the `files_list_folder` method](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.Dropbox.files_list_folder).
