### ISSUE TITLE
List folders throw 'Invalid select user id format'

### ISSUE THREAD

**Issue by robert2206** [dropbox/dropbox-sdk-python#166]
My code is following:

`dbx = dropbox.DropboxTeam('my_token')
 print(dbx.as_admin('team_member_id').files_list_folder(''))`

I insert my token code and team member id but throw this exception 'Error in call to API function "files/list_folder": Invalid select user id format'

**Comment by greg-db** [comment]
What does the actual `'team_member_id'` value you're supplying look like? It should start with `'dbmid:'`. You can get it from [`MemberProfile.team_member_id`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/team.html#dropbox.team.MemberProfile.team_member_id), e.g., as returned by [`team_members_list`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.DropboxTeam.team_members_list)/[`team_members_list_continue`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.DropboxTeam.team_members_list_continue) or [`team_members_get_info`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.DropboxTeam.team_members_get_info), for instance.

If you provide a different kind of value, you'll get this error.

**Comment by robert2206** [comment]
Thanks, @greg-db  
team_members_list method return for me correct user id format
