### ISSUE TITLE
Getting ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by lacasta** [dropbox/dropbox-sdk-python#169]
I am trying to use this in a mac osx 10.14.5 running python3.7 as ported by brew. I installed the package via pip3. No problem. However when importing the dropbox I get the following

Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dropbox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dropbox/dropbox.py", line 20, in <module>
    from . import files, stone_serializers
ImportError: attempted relative import with no known parent package

**Comment by db-api-support-github-notifications** [comment]
It looks like that issue has to do with using relative imports. I thought this 
article <https://napuzba.com/a/import-error-relative-no-parent> did a good 
job of explaining the exception and offering solutions. Hope that helps!

**Comment by tiwary9847** [comment]
i am geeting this error
from .models import Customer,Profession,dataSheet,Document
ImportError: attempted relative import with no known parent package

**Comment by greg-db** [comment]
@tiwary9847 This is an issue for the "dropbox-sdk-python" repository, which is the official Dropbox API v2 Python SDK. Based on the names in the code you shared though, your code/error doesn't seem to be related to Dropbox, so I'm afraid we can't be of help with that.
