### ISSUE TITLE
Functions "files_export", "files_export_to_file" missed in documentations

### ISSUE THREAD

**Issue by rappongy** [dropbox/dropbox-sdk-python#171]
Hi!
Cannot find in documentations below functions: "files_export", "files_export_to_file"
Links: 
- [Docs » Index](https://dropbox-sdk-python.readthedocs.io/en/latest/genindex.html)
- Google [site:dropbox-sdk-python.readthedocs.io files_export](https://www.google.com/search?q=site%3Adropbox-sdk-python.readthedocs.io+files_export)

Otherwise functions "files_download", "files_download_to_file" are on place.

**Comment by greg-db** [comment]
Thanks for the report! It looks like the doc generation isn't working properly. I'll ask the team to fix that up. 

In the meantime, you can find the docstrings for these methods here:

https://github.com/dropbox/dropbox-sdk-python/blob/a58eb061860e27e8f5ef2e1817625a7a614c2d0b/dropbox/base.py#L1301

**Comment by rogebrd** [comment]
Appears to be fixed now, here is the links to each of the following functions:
files_export: [link](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.Dropbox.files_export)
files_export_to_file: [link](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.Dropbox.files_export_to_file)

Please let me know if you cannot see these or are looking for something else
