### ISSUE TITLE
dbx.files_upload fails on Kivy Android

### ISSUE THREAD

**Issue by maritimerabroad** [dropbox/dropbox-sdk-python#172]
Hello,

I made an app that generates forms, then uploads them to Dropbox. The app is made with Python and Kivy. The code works flawlessly when running under my PC, but when I test it on my Android device I get the following error:

**10-07 11:37:47.109 10926 10957 I python  :  requests.exceptions.ConnectionError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xcc7ff430>: Failed to establish a new connection: [Errno 7] No address associated with hostname'))

10-07 11:37:47.109 10926 10957 I python  : Python for android ended.**

Its very frustrating, can you please help?

**Comment by greg-db** [comment]
The error message "No address associated with hostname" seems to indicate that the DNS lookup for the Dropbox API content server hostname ('content.dropboxapi.com') is failing. That hostname is currently resolving properly for me though, so it looks like this may be specific to the device, or the DNS server it's using.

Can you check on the DNS server that the device is using? Or, is the Internet connection on the device/app itself working? (E.g., does your app have the necessary permissions to access the Internet?)

**Comment by maritimerabroad** [comment]
Oh my, this feels like a facepalm moment for me. I had to uncomment the permissions line in buildozer.spec to allow network access. After that, it works!

Thank you so much Greg!
