### ISSUE TITLE
Import Dropbox Module

### ISSUE THREAD

**Issue by JoeLajoe** [dropbox/dropbox-sdk-python#173]
Hi, I am unable to import the dropbox apk in a python 3.7.3 environment but works fine in 2.7.16 any ideas?

**Comment by greg-db** [comment]
I'll be happy to help with any issues you're having with the Dropbox API, but I'll need some more information. Please reply with:

- the version number of the Dropbox library you're using
- the steps to reproduce the issue, including relevant code snippet(s)
- the full text of any error or unexpected output

**Comment by JoeLajoe** [comment]
Sure I am using the latest Dropbox Library. I followed the steps provided by the GitHub. "pip install dropbox" after that I do an import github but I get an error saying "Unable to import DropBox"

**Comment by greg-db** [comment]
Thanks. To clarify though, when you say you 'do an import github', did you mean to say 'import dropbox'?

Also, is that the exact error message you get? The Dropbox library is `dropbox`, and the product is "Dropbox", never "DropBox".

Anyway, if you have multiple versions of Python, you may need to specify which version you want to use when installing packages via `pip`. For instance, for Python 3, you may need to do `pip3 install dropbox`.

**Comment by JoeLajoe** [comment]
Omg, that did it, I can't believe I didn't try that sorry to of wasted your time.
