### ISSUE TITLE
Skip upload if file exists

### ISSUE THREAD

**Issue by Fukitsu** [dropbox/dropbox-sdk-python#175]
I want to upload a file but only if it doesn't exist. I'm trying with
` dbx.files_upload(f.read(), BACKUPPATH, mode=WriteMode('add', None))`
But if the file exists I get an ApiError like
`UploadError('path', UploadWriteFailed(reason=WriteError('conflict', WriteConflictError('file', None))`
How can I upload the file only if it doesn't exist and if it does just skip it (do nothing)?

**Comment by greg-db** [comment]
Using the 'add' `WriteMode` like you already are in your example is the right way to do this. That tells Dropbox you want to add a new file, but not if something is already there. Accordingly, Dropbox rejects the upload with this 'conflict' error if a file already exists at that path. 

In your app's code, you should catch this error (using `except`) so you can handle this error case however you wish. For instance, you can just ignore the exception if that's what you want your app to do.
