### ISSUE TITLE
Business API Selecting User

### ISSUE THREAD

**Issue by maxnachamkin** [dropbox/dropbox-sdk-python#176]
Hi,

I'm connecting to our business's API using the access token, and getting this in response:

This API function operates on a single Dropbox account, but the OAuth 2 access token you provided is for an entire Dropbox Business team. 

I checked the docs and it mentions submitting an HTTP header or using select_user, but I couldn't find anything in regards to implementing that within this Python module. Any ideas?

**Comment by greg-db** [comment]
Yes, if you want to use [the "member file access" feature](https://www.dropbox.com/developers/documentation/http/teams#teams-member-file-access) with the Python SDK, you can do so via [the `DropboxTeam.as_user` method](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox.DropboxTeam.as_user), which sets the `Dropbox-API-Select-User` header, or [the `DropboxTeam.as_admin` method](), which sets the `Dropbox-API-Select-Admin` header.
