### ISSUE TITLE
Sample code outdated

### ISSUE THREAD

**Issue by Lucurus** [dropbox/dropbox-sdk-python#178]
Hi, the python code [here](https://dropbox-sdk-python.readthedocs.io/en/latest/api/oauth.html#dropbox.oauth.DropboxOAuth2FlowNoRedirect) is outdated and still uses python2.

**Example:**

`print "1. Go to: " + authorize_url` should be `print("1. Go to: " + authorize_url)`

**Comment by greg-db** [comment]
Thanks for pointing that out! I'll ask the team to fix that up.

**Comment by Lucurus** [comment]
No problem, thanks for your help!

**Comment by rogebrd** [comment]
Sample code is updated as a part of ongoing PR: https://github.com/dropbox/dropbox-sdk-python/pull/185
