### ISSUE TITLE
dbx.files_upload_session_append_v2 Is it a random server been connected?

### ISSUE THREAD

**Issue by louishot** [dropbox/dropbox-sdk-python#180]
Hello,

I'm use dbx.files_upload_session_append_v2 to upload large file But the speed is very unstable.
I used 30MB as CHUNK_SIZE. My server has a 1Gbps internet and very idle. so I suspect it is sometimes connected to a bad dropbox server node or a very high load dropbox server node.

I checked the sdk source code and wanted to find out the server address of each connection to it into dbx.files_upload_session_append_v2.
No solution found at this time
```
uploading: 1 of media/m002.mp4
uploaded: 31457280 of media/m002.mp4 used time 6.745985269546509
uploading: 31457280 of media/m002.mp4
uploaded: 62914560 of media/m002.mp4 used time 3.0077970027923584
uploading: 62914560 of media/m002.mp4
uploaded: 94371840 of media/m002.mp4 used time 2.6795079708099365
uploading: 94371840 of media/m002.mp4
uploaded: 125829120 of media/m002.mp4 used time 2.5502266883850098
uploading: 125829120 of media/m002.mp4
uploaded: 157286400 of media/m002.mp4 used time 30.76577353477478
uploading: 157286400 of media/m002.mp4
uploaded: 188743680 of media/m002.mp4 used time 4.496345520019531
uploading: 188743680 of media/m002.mp4
uploaded: 220200960 of media/m002.mp4 used time 2.933668375015259
uploading: 220200960 of media/m002.mp4
uploaded: 251658240 of media/m002.mp4 used time 2.999969959259033
uploading: 251658240 of media/m002.mp4
uploaded: 283115520 of media/m002.mp4 used time 39.48408651351929
uploading: 283115520 of media/m002.mp4
uploaded: 314572800 of media/m002.mp4 used time 6.2456958293914795
uploading: 314572800 of media/m002.mp4
uploaded: 346030080 of media/m002.mp4 used time 3.3357770442962646
uploading: 346030080 of media/m002.mp4
uploaded: 377487360 of media/m002.mp4 used time 2.5063118934631348
uploading: 377487360 of media/m002.mp4
```

**Comment by louishot** [comment]
[root@centos7 ~]# ping content.dropboxapi.com    
PING edge-block-api.dropbox-dns.com (162.125.82.8) 56(84) bytes of data.
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=1 ttl=59 time=0.855 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=2 ttl=59 time=0.644 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=3 ttl=59 time=0.925 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=4 ttl=59 time=0.761 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=5 ttl=59 time=0.754 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=6 ttl=59 time=0.638 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=7 ttl=59 time=0.822 ms
64 bytes from 162.125.82.8 (162.125.82.8): icmp_seq=8 ttl=59 time=0.732 ms

Seems to be an internal issue with the dropbox server. I see network latency very good.

Server node looks like is fixed 
[root@centos7 ~]# nslookup content.dropboxapi.com
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
content.dropboxapi.com  canonical name = edge-block-api.dropbox-dns.com.
Name:   edge-block-api.dropbox-dns.com
Address: 162.125.82.8
Name:   edge-block-api.dropbox-dns.com
Address: 2620:100:6032:8::a27d:5208

**Comment by greg-db** [comment]
There are a number of different things that will affect the actual connection performance you see. I can ask the team to check on this though. Can you share the output of `traceroute content.dropboxapi.com` first though? Thanks!

**Comment by louishot** [comment]
> There are a number of different things that will affect the actual connection performance you see. I can ask the team to check on this though. Can you share the output of `traceroute content.dropboxapi.com` first though? Thanks!

traceroute to content.dropboxapi.com (162.125.82.8), 30 hops max, 60 byte packets
 1  gateway (45.65.45.1)  34.678 ms  34.827 ms  34.887 ms
 2  103.211.0.12 (103.211.0.12)  1.340 ms  1.086 ms  1.206 ms
 3  v702.core1.hkg1.he.net (65.49.109.205)  0.707 ms  0.586 ms  0.585 ms
 4  * * *
 5  ae1-hkg1-ea01.net.dropbox.com (162.125.86.153)  1.027 ms  0.994 ms  1.036 ms
 6  content.dropboxapi.com (162.125.82.8)  0.858 ms  0.660 ms  0.648 ms

**Comment by greg-db** [comment]
Thanks! I'll ask the team to check if there's an issue on our side.

**Comment by greg-db** [comment]
@louishot The team is looking into this but could use some more information. Can you also share:
- the IP address of your server
- some `x-dropbox-request-id` response header values for the slow requests?

You should be able to get the headers by enabling debug output like this:
```
try:
    import http.client as http_client
except ImportError:
    # Python 2
    import httplib as http_client
http_client.HTTPConnection.debuglevel = 1
```

Also, if you'd prefer to share privately, you can open an API ticket here: https://www.dropbox.com/developers/contact

**Comment by louishot** [comment]
> http_client.HTTPConnection.debuglevel = 1

true on debug but output POST bodies, Hundreds of millions of outputs difficult to find useful information

**Comment by greg-db** [comment]
@louishot Can you try with just one call and then filter or grep the output for 'x-dropbox-request-id'?

**Comment by louishot** [comment]
> @louishot Can you try with just one call at a time and then filter or grep the output for 'x-dropbox-request-id'?

I 'm trying to find the x-dropbox-request-id that match the request time

**Comment by louishot** [comment]
I temporarily deleted output POST bodies in debug model, and I created Ticket #10461552
```
if self.debuglevel > 10:
            print("send:", repr(data))
```

**Comment by greg-db** [comment]
Great, thanks. We'll follow up with you there.

**Comment by SaveTheRbtz** [comment]
@louishot Just in case, can you try:
```
sudo sysctl net.ipv4.tcp_slow_start_after_idle=0
```

**Comment by SaveTheRbtz** [comment]
@louishot Also if you can attach a gist with an output of 
```ss -montie 'dst 162.125.82.8'```
during the upload, this may greatly simplify debugging on our side.

**Comment by louishot** [comment]
```
ss -montie 'dst 162.125.82.8'
State      Recv-Q Send-Q Local Address:Port               Peer Address:Port              
ESTAB      0      0      x.x.x.x:36839              162.125.82.8:443                 ino:153020871 sk:ffff8844c490ec80 <->
         skmem:(r0,rb367360,t0,tb4194304,f0,w0,o0,bl0,d0) ts sack cubic wscale:9,7 rto:250 rtt:49.514/0.051 ato:40 mss:1388 rcvmss:1388 advmss:1448 cwnd:3643 ssthresh:3643 bytes_acked:252107957 bytes_received:7421 segs_out:183963 segs_in:21160 send 817.0Mbps lastsnd:891 lastrcv:1969 lastack:841 pacing_rate 1634.0Mbps reordering:17 rcv_rtt:52 rcv_space:29200
```

**Comment by SaveTheRbtz** [comment]
@louishot ok, networking-wise you look fine: no packetloss, good pacing rate.
(the only interesting thing is that `ss` and `traceroute` disagree about rtt.)

Just to rule out the buffering problems, can you try uploading in smaller chunks?  e.g. 4Mb?

**Comment by louishot** [comment]
> @louishot ok, networking-wise you look fine: no packetloss, good pacing rate, decent buffers.
> (the only interesting thing is that `ss` and `traceroute` disagree about rtt.)
> 
> Just to rule out the buffering problems, can you try uploading in smaller chunks? e.g. 4Mb?

I don't have change everything but speed looks like more stable than before
`encrypt media/498.mp4 OK! used 25.20841121673584
uploading: 1 of media/498_.mp4
uploaded: 31457280 of media/498_.mp4 used time 3.8386740684509277
uploading: 31457280 of media/498_.mp4
uploaded: 62914560 of media/498_.mp4 used time 3.069507598876953
uploading: 62914560 of media/498_.mp4
uploaded: 94371840 of media/498_.mp4 used time 3.571537971496582
uploading: 94371840 of media/498_.mp4
uploaded: 125829120 of media/498_.mp4 used time 2.727743148803711
uploading: 125829120 of media/498_.mp4
uploaded: 157286400 of media/498_.mp4 used time 2.5602760314941406
uploading: 157286400 of media/498_.mp4
uploaded: 188743680 of media/498_.mp4 used time 3.098871946334839
uploading: 188743680 of media/498_.mp4
uploaded: 220200960 of media/498_.mp4 used time 2.983858108520508
uploading: 220200960 of media/498_.mp4
uploaded: 251658240 of media/498_.mp4 used time 3.3933024406433105
uploading: 251658240 of media/498_.mp4
uploaded: 283115520 of media/498_.mp4 used time 3.0379090309143066
uploading: 283115520 of media/498_.mp4
uploaded: 314572800 of media/498_.mp4 used time 2.692620038986206
uploading: 314572800 of media/498_.mp4
uploaded: 346030080 of media/498_.mp4 used time 3.769263505935669
uploading: 346030080 of media/498_.mp4
uploaded: 377487360 of media/498_.mp4 used time 6.799442529678345
uploading: 377487360 of media/498_.mp4
uploaded: 408944640 of media/498_.mp4 used time 2.9492359161376953
uploading: 408944640 of media/498_.mp4
uploaded: 440401920 of media/498_.mp4 used time 2.9715969562530518
uploading: 440401920 of media/498_.mp4
uploaded: 471859200 of media/498_.mp4 used time 2.971341848373413
uploading: 471859200 of media/498_.mp4
uploaded: 503316480 of media/498_.mp4 used time 3.515880584716797
uploading: 503316480 of media/498_.mp4
uploaded: 534773760 of media/498_.mp4 used time 3.7973616123199463
uploading: 534773760 of media/498_.mp4
uploaded: 566231040 of media/498_.mp4 used time 2.542250871658325
uploading: 566231040 of media/498_.mp4
uploaded: 597688320 of media/498_.mp4 used`

**Comment by louishot** [comment]
> > @louishot ok, networking-wise you look fine: no packetloss, good pacing rate, decent buffers.
> > (the only interesting thing is that `ss` and `traceroute` disagree about rtt.)
> > Just to rule out the buffering problems, can you try uploading in smaller chunks? e.g. 4Mb?
> 
> I don't have change everything but speed looks like more stable than before
> 
> ```
> encrypt media/498.mp4 OK! used 25.20841121673584
> uploading: 1 of media/498_.mp4
> uploaded: 31457280 of media/498_.mp4 used time 3.8386740684509277
> uploading: 31457280 of media/498_.mp4
> uploaded: 62914560 of media/498_.mp4 used time 3.069507598876953
> uploading: 62914560 of media/498_.mp4
> uploaded: 94371840 of media/498_.mp4 used time 3.571537971496582
> uploading: 94371840 of media/498_.mp4
> uploaded: 125829120 of media/498_.mp4 used time 2.727743148803711
> uploading: 125829120 of media/498_.mp4
> uploaded: 157286400 of media/498_.mp4 used time 2.5602760314941406
> uploading: 157286400 of media/498_.mp4
> uploaded: 188743680 of media/498_.mp4 used time 3.098871946334839
> uploading: 188743680 of media/498_.mp4
> uploaded: 220200960 of media/498_.mp4 used time 2.983858108520508
> uploading: 220200960 of media/498_.mp4
> uploaded: 251658240 of media/498_.mp4 used time 3.3933024406433105
> uploading: 251658240 of media/498_.mp4
> uploaded: 283115520 of media/498_.mp4 used time 3.0379090309143066
> uploading: 283115520 of media/498_.mp4
> uploaded: 314572800 of media/498_.mp4 used time 2.692620038986206
> uploading: 314572800 of media/498_.mp4
> uploaded: 346030080 of media/498_.mp4 used time 3.769263505935669
> uploading: 346030080 of media/498_.mp4
> uploaded: 377487360 of media/498_.mp4 used time 6.799442529678345
> uploading: 377487360 of media/498_.mp4
> uploaded: 408944640 of media/498_.mp4 used time 2.9492359161376953
> uploading: 408944640 of media/498_.mp4
> uploaded: 440401920 of media/498_.mp4 used time 2.9715969562530518
> uploading: 440401920 of media/498_.mp4
> uploaded: 471859200 of media/498_.mp4 used time 2.971341848373413
> uploading: 471859200 of media/498_.mp4
> uploaded: 503316480 of media/498_.mp4 used time 3.515880584716797
> uploading: 503316480 of media/498_.mp4
> uploaded: 534773760 of media/498_.mp4 used time 3.7973616123199463
> uploading: 534773760 of media/498_.mp4
> uploaded: 566231040 of media/498_.mp4 used time 2.542250871658325
> uploading: 566231040 of media/498_.mp4
> uploaded: 597688320 of media/498_.mp4 used
> ```

Forgot say that is night speed in Hong Kong time 02:50 PM. Not sure if the network is busy during the day, but I will do a test during the day to compare day and night speed.
