### ISSUE TITLE
post() calls are missing timeout parameters

### ISSUE THREAD

**Issue by earonesty** [dropbox/dropbox-sdk-python#191]
The code for `refresh_access_token` is missing a timeout.   

The code for some other requests uses a default timeout of None, but the DEFAULT_TIMEOUT for the Dropbox main sdk object is 100 seconds -and gets passed down, which should be fine.  

Suggestion: add a `pylint-requests` plugin linter rule to find all of these issues + add a default timeout, or an exception if a timeout is not specified to lower-level libs, rather than silently allowing None.

The effect of a missing timeout is a potential to block forever in the event that a request is dropped by the TCP stack.   This can happen on a far more regular basis than people may think (for example on machines that have a 'sleep' mode, like a laptop).

Even if optionality is too complex to implement, a large default timeout value is significantly better than None.

**Comment by greg-db** [comment]
Thanks for writing this up and letting us know! I'll ask the team to fix this up.
