### ISSUE TITLE
Missing timeout in requests call

### ISSUE THREAD

**Issue by earonesty** [dropbox/dropbox-sdk-python#197]
If the server drops, this call can hang forever.

https://github.com/dropbox/dropbox-sdk-python/blob/417ab9c25e4986bc08bd99669e7d87b30a8faf2c/dropbox/oauth.py#L198

**Comment by greg-db** [comment]
Thanks for the report!

**Comment by greg-db** [comment]
This should be fixed as of v10.3.0.
