### ISSUE TITLE
Updown.py example fails silently for Mac OS Catalina user who has not permissioned /Downloads

### ISSUE THREAD

**Issue by kylenstone** [dropbox/dropbox-sdk-python#199]
Users new to Catalina or Dropbox's sample code might be thrown off by the lack of explicit error when running `/example/updown.py`.  Either in the example file itself or in the developer docs tutorial it would be good to indicate that Mac users should check permissions to the Downloads folder before trying the same code.

**Comment by greg-db** [comment]
Can you clarify what particular steps you're following that result in a silent failure? 

Also, are you referring to the permissions granted to Terminal in System Preferences > Security & Privacy > Privacy > Files and Folders? When I don't have that granted I do get an `OSError` when trying to run updown.py.

**Comment by kylenstone** [comment]
Yes, I'm referring to not having permissions granted to whatever IDE is used (in my case it was VSCode).  Given that it's sample code, it's likely that users might not understand the new Mac permissions model, so my suggestion was to make it explicit with an error, warning or comment that users should check their permissions before running the code.

**Comment by greg-db** [comment]
Thanks! I'm trying to reproduce the silent failure here, but I do get this error when I try to run without giving Visual Studio Code access:
```
...
    return os.listdir(path)
OSError: [Errno 1] Operation not permitted: '/Users/<username>/Downloads/dropbox-sdk-python-master/example'
```
Did that not occur in your case? If not, can you elaborate on what steps you followed that resulted in a silent failure? I'd like to make sure we can reproduce exactly what you're reporting as well so we can determine what additional documentation would be needed.

**Comment by rogebrd** [comment]
Closing due to no response by reporter.  If this is still an issue, please reopen this issue.
