### ISSUE TITLE
users_get_space_usage function broken in API V2

### ISSUE THREAD

**Issue by sentinelleader** [dropbox/dropbox-sdk-python#2]
Just observed that the `users_get_space_usage()` function is broken is API V2.

The expected field names are "**allocated**" and "**used**" as per [users.py](https://github.com/dropbox/dropbox-sdk-python/blob/master/dropbox/users.py#L937) for [_decode_struct_fields](https://github.com/dropbox/dropbox-sdk-python/blob/master/dropbox/babel_serializers.py#L381) function, but the API V2 is returning a nested JSON of the form

```
{
  'allocation': 
        {
        '.tag': 'individual', 
        'allocated': xxxxxxxxx
        }, 
  'used': xxxxxxxxxx
}
```

Where the parent key is **allocation** (which is not the expected Field) which results in the error 
`dropbox.babel_validators.ValidationError: missing required field 'allocated'`, as the expected key **allocated** becomes **None** because the [if condition](https://github.com/dropbox/dropbox-sdk-python/blob/master/dropbox/babel_serializers.py#L382) breaks

```
Sample Curl Request to the API

curl -X POST https://api.dropboxapi.com/2-beta-2/users/get_space_usage \
    --header "Authorization: Bearer xyxyxyxyxxyxyxyxyxxyxy" \
    --header "Content-Type: application/json" \
    --data "null"
{"used": xxxxxxx, "allocation": {".tag": "individual", "allocated": xxxxxxx}}

```

Has this new JSON Schema change happened with the API V2 ?

**Comment by varenc** [comment]
hey @sentinelleader, thanks for the report.  I do think this is a schema change issue.  We should be doing a new release soon that'll address this and make other updates as well.

**Comment by braincore** [comment]
We've updated the GitHub repository to support the new schema. Thanks again for the report @sentinelleader!
