### ISSUE TITLE
Use tox for runtests

### ISSUE THREAD

**Issue by braincore** [dropbox/dropbox-sdk-python#20]
From @ewjoachim: Would you be ok to using tox instead of calling "python2" and "python3" directly in runtests. For those using virtualenvs instead of globally installing packages, that can smooth this a lot.

**Comment by braincore** [comment]
Added `tox.ini` in b71ef6d875bdbb084d44e5b0f4a508f2eecfad5f.

**Comment by ewjoachim** [comment]
\o/
