### ISSUE TITLE
OAuth stopped working

### ISSUE THREAD

**Issue by earonesty** [dropbox/dropbox-sdk-python#203]
We didn't change anything, but it ceased.

https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=objo7li90yqmnfi&redirect_uri=http%3A%2F%2F127.0.0.1%3A53566%2Fauth%2F&state=6j1RcvE9boOYuJLkFqP3Tg%3D%3D

Was there an update or something?

**Comment by greg-db** [comment]
I see this page is showing the error:
> Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

Nothing should have changed on our side to make this fail suddenly.

This error indicates that the app for app key `objo7li90yqmnfi` does not have the redirect URI `http://127.0.0.1:53566/auth/` registered. You should either use a redirect URI that is registered for the app, or if you need to use this redirect URI, register it for the app. You can add redirect URIs from the app's page on [the App Console](https://www.dropbox.com/developers/apps).

If you're having trouble configuring your app, [open an API ticket](https://www.dropbox.com/developers/contact) from the account that owns the app.
