### ISSUE TITLE
Issue when trying to access dropbox from within a forked process (using pythons multiprocessing queues and workers)

### ISSUE THREAD

**Issue by SevenChords** [dropbox/dropbox-sdk-python#209]
when it reaches the point where i try to get the filenames from the dropbox folder (using dbx.files_list_folder('').entries) from within multiple sub processes it just crashes python, giving out some error that has appeared online for different situations, however, the fixes that have been posted there have not been working for this case. the error it prints in console is "objc[<some number>]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead."
multiple cases of this issue that i found online have been fixed, suspected cause being some thread safety stuff in macos high sierra, however, none of those fixes worked here.
any idea how i can fix this?

**Comment by greg-db** [comment]
I'll be happy to help with any issues you're having with the Dropbox API/SDK, but I'll need some more information. Please reply with:

- the name and version number of the platform and SDK/library you are using
- the steps to reproduce the issue, including relevant code snippet(s)
