### ISSUE TITLE
files_get_preview says CSV is unsupported extension

### ISSUE THREAD

**Issue by KStenK** [dropbox/dropbox-sdk-python#212]
Hello,

We have a problem with previewing CSV format files.

The method we are using is `dropbox.dropbox.Dropbox.files_get_preview`.

I remember in the past that everything was working fine, but now it throws `PreviewError('unsupported_extension', None)` error.

In the documentation, I see that CSV format still should be supported.

Is it only us or anyone has the same issues?

**Comment by greg-db** [comment]
Thanks for the report! This looks like a bug on our side. We'll look into it, and I'll follow up here once I have an update for you.

**Comment by KStenK** [comment]
Hey @greg-db,

Any updates so far?

**Comment by greg-db** [comment]
@KStenK We were able to reproduce the issue, and the team is investigating, but I don't have any real news on this quite yet. I'll let you know as soon as I do.

**Comment by KStenK** [comment]
Any updates so far? :)

**Comment by greg-db** [comment]
@KStenK This is still open with the team, but I unfortunately don't have an update on it yet. I'll let you know when I do.

**Comment by greg-db** [comment]
This should be fixed now. Please try again and let me know if you're still seeing any issues.

**Comment by KStenK** [comment]
Everything seems to work now.

Thank you!
