### ISSUE TITLE
Update tox.ini and README.rst python badge to python3.7 and python 3.8

### ISSUE THREAD

**Issue by Lucurus** [dropbox/dropbox-sdk-python#215]
Hi, 

this is purely cosmetic but [tox.ini](https://github.com/dropbox/dropbox-sdk-python/blob/master/tox.ini) and the python badge on [README.rst](https://github.com/dropbox/dropbox-sdk-python/blob/master/README.rst) both show only python3.6 as the highest possible version, whereas the docs state that python3.4+ is supported.

Shouldn't make a big difference but would keep them synced.

**Comment by greg-db** [comment]
We've fixed this up. Thanks again for pointing this out!
