### ISSUE TITLE
Client attempts to raise `BadStateError` instead of `BadStateException`

### ISSUE THREAD

**Issue by ehaas** [dropbox/dropbox-sdk-python#22]
dropbox/client.py line 1567 `raise self.BadStateError("Missing CSRF token in session.")` should be raising `BadStateException` instead. Currently produces an AttributeError.

**Comment by ehaas** [comment]
Note: similar issue on line 1601: `raise self.ProviderError(full_message)` should be `ProviderException`

**Comment by braincore** [comment]
Thanks for the bug report! This one dates back to 2013 :) It's fixed in 3.37.
