### ISSUE TITLE
New line in docs is incorrectly broken in readthedocs

### ISSUE THREAD

**Issue by Lucurus** [dropbox/dropbox-sdk-python#227]
Hi,

the argument `expiration` in [OAuth2FlowNoRedirectResult](https://dropbox-sdk-python.readthedocs.io/en/latest/api/oauth.html#dropbox.oauth.OAuth2FlowNoRedirectResult) is split into two lines in the documentation, which should not happen. I think this is because of the new line in the [code](https://github.com/dropbox/dropbox-sdk-python/blob/7b75667e766572b7df3a75ee03ff6098088c5d61/dropbox/oauth.py#L52) itself.

I'm not sure how readthedocs treats new lines which is why I didn't create a pull request myself.

Screenshot:
<img width="576" alt="Screenshot" src="https://user-images.githubusercontent.com/10774221/92626268-fa4e3880-f2c9-11ea-9824-2d46c8fd9dca.png">

Thanks!

**Comment by Lucurus** [comment]
Also, question from my side: When is a time in seconds returned and when a datetime? Is there a rule one can follow?

**Comment by greg-db** [comment]
Thanks for pointing out this formatting issue! I'll ask the team to fix that up.

Also, we don't have a documented guarantee on when which type would be used, so I recommend checking the type, [like the SDK does here](https://github.com/dropbox/dropbox-sdk-python/blob/d63479180b14052cb888c0c2ac36d7e9404d5cdb/dropbox/oauth.py#L65).

**Comment by Lucurus** [comment]
Pleasure!

Ok, thanks for the link, I'll just `isinstance()` it then.
