### ISSUE TITLE
Include conda and conda-forge in download options?

### ISSUE THREAD

**Issue by BastianZim** [dropbox/dropbox-sdk-python#244]
Hi, 

I was wondering if there's an interest to include conda and/or conda-forge as download options in the readme and in the badges?

I could create the pull request but just wanted to check if that's something Dropbox is interested in?

**Examples**:

* Conda: ![Conda](https://img.shields.io/conda/v/main/dropbox)

* Conda-forge: ![Conda](https://img.shields.io/conda/v/conda-forge/dropbox)

**Comment by greg-db** [comment]
Thanks! I'll ask the team if this is something they'd be interested in.

**Comment by rogebrd** [comment]
I am not entirely familiar with the Conda environment.  Does it pull from PyPi to populate its repositories or is it published manually?

**Comment by Lucurus** [comment]
Depends on which channel one is using.

Conda packages are built by Anaconda using their internal processes but the source should be Github or PyPi if I'm not mistaken. See: https://www.anaconda.com/blog/understanding-conda-and-pip
Updates are manually done by the anaconda team or can be requested in their repo, for example: https://github.com/ContinuumIO/anaconda-issues/issues/12081.

Conda-forge is a community-run channel that gets their packages from PyPi. Updates can be automatically updated or manually approved, depending on what the owner wants. See: https://github.com/conda-forge/dropbox-feedstock and https://conda-forge.org/#contribute
