### ISSUE TITLE
Tag API releases?

### ISSUE THREAD

**Issue by KyleWpppd** [dropbox/dropbox-sdk-python#25]
Hey Dropbox Devs,

Congrats on your v2 release. Would it be possible to add pip versions as Git tags in future releases? 

It would be really nice to be able to browse what's in a release here on Github rather than downloading it from pip.

Thanks!

**Comment by braincore** [comment]
We'll start tagging with the next release :) I'll close this issue when that happens.

**Comment by KyleWpppd** [comment]
Thank you @braincore! :100:

**Comment by braincore** [comment]
The latest release of the SDK (version 3.39) was just released on PyPI and GitHub and is tagged. Happy coding!
