### ISSUE TITLE
It is no longer possible to upload a file that is composed of an in-memory StringIO stream.

### ISSUE THREAD

**Issue by jperras** [dropbox/dropbox-sdk-python#27]
In the previous version of the API, it was possible to create an in-memory stream and use that as a file-like object for [creating a new file](https://www.dropbox.com/developers-v1/core/docs/python#DropboxClient.put_file):

```python
import StringIO
stream = StringIO.StringIO()
stream.write(u'This is a test.\n')
response = client.put_file(u'/magnum-opus.txt', stream)
print "uploaded:", response
```

With the new API, the use of a `StringIO` stream produces an error:

```python
data = StringIO.StringIO()
data.write(u'This is a test.\n')
path = u'/testing.txt'
client.files_upload(data, path)

# raises a ConnectionError
> ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

The solution is, somewhat obviously, to simply eschew the stream construct and pass the unicode data directly to the `data` parameter of `files_upload()` via `StringIO.getvalue()`. However, I can't think of a reason why the file-like object should produce such an error instead of extracting out the correct value.

**Comment by braincore** [comment]
In the examples you've provided, you're actually passing a `StringIO` object that's seeked to the end of the stream. To demontrate:

```
> from StringIO import StringIO
> s.write('hello')
> s.tell()
5
> s.read()
''
```

You need to rewind the stream so that there's data to read:
```
s.seek(0)
```

Alternatively, if you pass the string into the `StringIO` init, the position is at byte 0. So this works:
```
path = u'/testing.txt'
client.files_upload(StringIO.StringIO('This is a test.\n'), path)
```

Now, it does look like you stumbled on a bug whereby a `StringIO` with no additional data to read will cause the request to fail. I'll update the thread when I know more.

**Comment by jperras** [comment]
Ah, the missing `seek` causing that makes sense; it seems as though the previous `dropbox.put_file()` implementation rewound the stream (or similar, I haven't actually checked), and thus masked our slight abuse of the `StringIO` API.

Rewinding the stream is definitely the correct solution here; I only wanted to signal that there was a change in behaviour between the v1 and v2 APIs for the methods that handled file uploads.

> Now, it does look like you stumbled on a bug whereby a StringIO with no additional data to read will cause the request to fail. I'll update the thread when I know more.

Great. Thanks!

**Comment by braincore** [comment]
It looks like this behavior is exhibited in the `requests` package we depend on. I've filed an issue there. If it doesn't get resolved there, I'll consider re-opening this and fixing it in our layer.

**Comment by jperras** [comment]
Thanks for the update & the linked issue!

**Comment by braincore** [comment]
Cool, looks like there is a pull request and it's going to go in as a fix :)
