### ISSUE TITLE
Some files being reported as `restricted_content` by mistake

### ISSUE THREAD

**Issue by Sarke** [dropbox/dropbox-sdk-python#279]
**Describe the bug**
Some files are marked as `restricted_content` by mistake, and unable to download.  They are not marked on the webapp as such, and the official app downloads them fine too.

**To Reproduce**
Try syncing these files: 
https://cdnjs.cloudflare.com/ajax/libs/jquery.ba-bbq/1.2.1/jquery.ba-bbq.min.js
https://cdnjs.cloudflare.com/ajax/libs/cufon/1.09i/cufon-yui.js

**Expected Behavior**
It syncs.

**Actual Behavior**
It returns `restricted_content`.

**Screenshots**
N/A

**Versions**
* What version of the SDK are you using? 10.6.0
* What version of the language are you using? Python 3.8.2
* What platform are you using? (if applicable) Ubuntu

**Additional context**
N/A

**Comment by greg-db** [comment]
Thanks for the report! This should be fixed now.
