### ISSUE TITLE
Fastest way to check for existence of a file?

### ISSUE THREAD

**Issue by tomkinsc** [dropbox/dropbox-sdk-python#28]
I'm writing a Dropbox provider for the bioinformatics workflow engine, [Snakemake](https://bitbucket.org/johanneskoester/snakemake/). When a Snakemake workflow is executed it builds its directed acyclic graph of rules to execute based on which files exist. Consequently, it can check for the existence of many files, often several times. I want a fast way to check whether or not a file exists on Dropbox.

What is the best practice for checking file existence on Dropbox via the Python SDK for the v2 API? 

So far, I have the following candidate functions (stripped-down example):

```python
import dropbox

dbx = dropbox.Dropbox(oauth2_access_token="mytoken")

path = "/path/to/my/file.bam"

def exists(path):
    return os.path.basename(path) in [e.name for e in dbx.files_list_folder(path=os.path.dirname(path)).entries]

def exists2(path):
    try:
        dbx.files_get_metadata(path)
        return True
    except:
        return False

```

Is there a faster way? Thanks!

**Comment by cakoose** [comment]
*In general*, there's no faster way to do it.

However, for some use cases it might be worth maintaining a local cache of the entire directory tree (just file metadata, not file data).  This has the potential to be much more efficient.  For example, you might only need a single API call to list *all* the files that have changed.

Our [old API v1 SDK](https://www.dropbox.com/developers-v1/core/sdks/python) has an example of how to maintain a local cache in "examples/search_cache.py".  It uses API v1, but there are equivalent API v2 functions:
- `/delta` &rarr; `/list_folder?recursive=true`
- `/delta?cursor=...` &rarr; `/list_folder/continue?cursor=...`

**Comment by braincore** [comment]
By the way, if you're only looking to do a single path look up, you should use `exists2()`. As it is, `exists()` is incorrectly implemented. `files_list_folder()` is paginated, which means that if the folder has a lot of files, you won't necessarily see the file after the first query. You may need to call `files_list_folder_continue()` until you've seen all the files.

Just wondering, is the "file existence lookup" a performance bottleneck? How many files (order of magnitude) are typically looked up per workflow? How long does the execution of a workflow typically take?

**Comment by tomkinsc** [comment]
The documentation could definitely be improved then, it wasn't clear from the section for [`files_list_folder()`](https://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.base.DropboxBase.files_list_folder) that the results are paginated. How would I go about paging though the them? 

I'll go with the second method.

Checking if files exist is not a significant bottleneck, but it is one of the slower operations. The files can number from one to millions, depending on the specific application for a workflow. 

I guess I just find it surprising that there isn't a nice constant-time `exists(filepath)` function, especially considering that S3 [already supports it](https://github.com/boto/boto/blob/develop/boto/s3/key.py#L532) and rumor has it Dropbox is S3-backed.

Are there plans to make the library more Pythonic? The deep object hierarchy and use of cursors feels very java-esque, in an unfortunate way.

**Comment by braincore** [comment]
Good point--we'll improve the docs. You page through entries by taking the `cursor` from the result of `files_list_folder()` and passing it in as an argument to `files_list_folder_continue()`.

Your `exists2()` function is "constant time." What slows you down is the network latency of making that request to Dropbox. It will take on the order of tens to hundreds of milliseconds depending on your connection for the request/response round trip, ie. network transit time. You'll have this exact same problem when trying to query S3 one file at a time.

There are a couple of ways to tackle this problem. You can try to make many parallel requests to Dropbox using a threadpool, but we'll rate limit you to about 100 requests/sec. Or, you could go with @cakoose's suggestion and sync down all the metadata for a user's Dropbox, which is more expensive upfront, but then the existence checks are cheap.

**Comment by tomkinsc** [comment]
Thanks, hopefully it won't become a bottleneck, but caching metadata sounds like a good option for down the road.

I understand that the second way is constant time (why I did it), but it would still be nice to have a convenience function to check for existence of a file. All of the other operations I'd expect for a filesystem-like API were there in the metadata--modification time, size, etc. Others may benefit from the addition of such a function.

**Comment by braincore** [comment]
By the way, great seeing bioinformatics software integrate with Dropbox :) Is this associated with Broad?
