### ISSUE TITLE
Links to pull requests in the release notes are not working

### ISSUE THREAD

**Issue by SamSchott** [dropbox/dropbox-sdk-python#286]
The links to PRs in the release notes are not working. For example, the latest 10.9.0 release links to #284 with the url

https://github.com/dropbox/dropbox-sdk-python/blob/v10.9.0/github.com/dropbox/dropbox-sdk-python/pull/284

which leads nowhere.

**Comment by rogebrd** [comment]
Hello Sam,

I have updated the links for the release of 10.9.0 and will fix the script that generates the release notes!

**Comment by SamSchott** [comment]
Thanks!
