### ISSUE TITLE
New stone dependency

### ISSUE THREAD

**Issue by SamSchott** [dropbox/dropbox-sdk-python#299]
**Describe the bug**
Stone is no longer bundled with dropbox but seems to be an external dependency now, imported in `dropbox/stone_validators.py` and `dropbox/stone_serializers.py`. However, it is not listed as a requirement in `setup.py` and therefore leads to an import error on a fresh install.

**Versions**
* What version of the SDK are you using? v10.11
* What version of the language are you using? 3.9

**Comment by greg-db** [comment]
Thanks! We're fixing this in #300, which should be in the next release.

**Comment by greg-db** [comment]
This is fixed with v11.0.0. Thanks again.

**Comment by SamSchott** [comment]
Thanks!
