### ISSUE TITLE
Is current version up to date?

### ISSUE THREAD

**Issue by Wilbeibi** [dropbox/dropbox-sdk-python#3]
When I installed via `git clone` and `python setup.py install`, the version is 0.1, but when I search the `dropbox2` in pip, it said the latest version is 1.7.1.

**Comment by Wilbeibi** [comment]
And by the way, the Dropbox page said to `pip install dropbox`, which I believe is an older version, with some different APIs.

**Comment by braincore** [comment]
Where did you read the suggestion to `pip install dropbox`? Because the v2 SDK is currently a "developer preview" we haven't switched the package available in PyPI to it yet. We don't want to inadvertently break users who may not be expecting the backwards incompatible change.

**Comment by braincore** [comment]
Is it okay if I close this issue and ping it once we've decided to make v2 the default installed by PyPI?

**Comment by Wilbeibi** [comment]
Here https://www.dropbox.com/developers/core/sdks/python 

No problem. It totally fine to close it.
