### ISSUE TITLE
Internal Server error when using files_move and files_copy

### ISSUE THREAD

**Issue by kg-2** [dropbox/dropbox-sdk-python#30]
Hi,
   I'm receiving an InternalServerError everytime I call files_move or files_copy. I'm currently working around the issue from downloading and re-uploading each file instead. Here is my traceback

  File "C:\Python27\lib\custom\dropbox_backup.py", line 69, in move_sequential_files
    self.dropbox.rename(file_path, this_path)
  File "C:\Python27\lib\custom\dropbox\dropbox_wrapper.py", line 113, in rename
    self.client.files_move(old_path, new_path)
  File "C:\Python27\lib\site-packages\dropbox\base.py", line 544, in files_move
    None)
  File "C:\Python27\lib\site-packages\dropbox\dropbox.py", line 175, in request
    request_binary)
  File "C:\Python27\lib\site-packages\dropbox\dropbox.py", line 256, in request_json_string_with_retry
    request_binary)
  File "C:\Python27\lib\site-packages\dropbox\dropbox.py", line 320, in request_json_string
    raise InternalServerError(r.status_code, r.text)
InternalServerError

**Comment by braincore** [comment]
Thanks for the report! This is a server-side issue and we're currently tracking it. I'll update this thread as progress is made.

**Comment by kg-2** [comment]
awesome, thanks!

**Comment by braincore** [comment]
This is resolved.

**Comment by braincore** [comment]
Oh sorry, it isn't yet.

**Comment by braincore** [comment]
I assume not all `file_move` requests are failing. Do you see this occurring with specific files or folders?

**Comment by jperras** [comment]
I just ran my tests for this functionality, and it worked as expected.

**Comment by jperras** [comment]
I just managed to trigger the error – it seems to be intermittent.

**Comment by kg-2** [comment]
I'm still getting the error 100% of the time.

**Comment by kg-2** [comment]
To answer the previous question; every time I call file_move or file_copy I get the error.

**Comment by braincore** [comment]
@kg-2 Okay, we know why you're getting this error. I'll let you know when the fix goes out. @jperras Is your app an App Folder app?

**Comment by jperras** [comment]
@braincore Pardon the delayed response – yes, our application is configured as an App folder app. I don't believe my test has passed since [my previous comment](https://github.com/dropbox/dropbox-sdk-python/issues/30#issuecomment-158234555).

**Comment by varenc** [comment]
if you can provide us with the value of the "X-Dropbox-Request-ID" header returned in the 500 response we can look up the 500 error directly on the our end!

**Comment by kg-2** [comment]
new feature request: add useful information to the exceptions ;)
2015-11-26 12:51:28,463 WARNING {'Transfer-Encoding': 'chunked', 'Server': 'nginx', 'Connection': 'keep-alive', 'X-Dropbox-Request-Id': 'cb8e17ace6f24b1c1276f7e647aecc69', 'Date': 'Thu, 26 Nov 2015 20:51:35 GMT', 'Content-Type': 'text/plain; charset=utf-8'}

**Comment by braincore** [comment]
Thanks! We've tracked this down, we're just a bit slow getting the fix out over Thanksgiving week :)

**Comment by kg-2** [comment]
ha completely understandable, enjoy the time off

**Comment by jperras** [comment]
@varenc Here's an `X-Dropbox-Request-Id` for a request that caused a `500 Internal Server Error`:

```python
{'Transfer-Encoding': 'chunked', 'Server': 'nginx', 'Connection': 'keep-alive', 'X-Dropbox-Request-Id': '280b76d456745c8761cfacd558d2c365', 'Date': 'Tue, 01 Dec 2015 04:24:00 GMT', 'Content-Type': 'text/plain; charset=utf-8'}
```

**Comment by clagos4** [comment]
Hi! I had the same problem, it seems to me that it only occurs when you are using the api in a sub folder of your whole dropbox, I changed the configuration to the whole dropbox and it let me move and copy. I hope this help you to find the fix of the problem! Good luck!

**Comment by jperras** [comment]
@varenc Any details about the error?

**Comment by braincore** [comment]
Thanks everyone for your patience and help! The fix is now in production. Please re-open the task if the behavior persists.

**Comment by jperras** [comment]
Thanks! Works like a charm now.
