### ISSUE TITLE
'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by hdd** [dropbox/dropbox-sdk-python#31]
running the example in http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#module-dropbox.oauth.DropboxOAuth2FlowNoRedirect:

breaks in self.build_path with:

AttributeError: 'str' object has no attribute 'copy'

seems happening in here:
@111   return "https://%s%s" % (self._host, self.build_path(target, params))

as self.build_url expect the second argument to be a dict (as by docstring) but actually is a string:
@50     url = self.build_url(Dropbox.HOST_API, '/oauth2/token')

Hope it helps.
L.

**Comment by braincore** [comment]
Thanks for the report! This is fixed in version 3.42 in GitHub and in PyPI.
