### ISSUE TITLE
Allow dropbox.base.files_move/files_copy to accept unique ID value in addition to path for source argument.

### ISSUE THREAD

**Issue by jperras** [dropbox/dropbox-sdk-python#32]
From the HTTP documentation it seems as though this isn't an issue with the Python SDK, but I'm not sure in which repository to request the feature.

`files_move()`, `files_copy` and the associated [HTTP API endpoints](https://www.dropbox.com/developers/documentation/http#documentation-files-move) of `files/move` and `files/copy` currently accepts paths as the source as destination arguments. Considering that `dropbox.files.FolderMetadata` and `dropbox.files.FileMetadata` now contain unique identifiers that represent the file or folder in question, it would be a welcome enhancement to allow the specification of the `id` value as the source (currently the `from_path` argument) for both endpoints.

If there's a more appropriate place to file this request, please let me know.

**Comment by smarx** [comment]
Thanks!

The API forum would be a better place for this feature request: https://www.dropboxforum.com/hc/en-us/community/topics/200209245-API-Development. I don't have an ETA for you, but we do plan on adding file ID support to the rest of the API methods.

**Comment by jperras** [comment]
Perfect, thanks!
