### ISSUE TITLE
files_move seems to copy files instead of moving them

### ISSUE THREAD

**Issue by Marto32** [dropbox/dropbox-sdk-python#321]
Has the behavior of [`files_move()`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html?#dropbox.dropbox.Dropbox.files_move) changed recently? It seems that in ~v8.5 this method used to actually move files. Now it seems to copy them - is this intended?

**Versions**
SDK version 9.0.0
Python 3.9

After authentication, I'm simply running the following and observing the above behavior:

```
import dropbox

source = '/path/to/source'
dest = '/path/to/dest'

dbx = dropbox.Dropbox(MY_TOKEN)
dbx.files_move(source, dest)
```

**Comment by greg-db** [comment]
The `files_move` method should still just move files, not copy them. I just gave this a try myself with v9.0.0 and it seems to be working properly for (moving, not copying files).

Can you share what you're seeing? If you're checking by code, could you share the rest of the code and the output, or if you're checking manually, could you perhaps share a short screencast or set of screenshots showing the call and unexpected copy result? Thanks in advance!

**Comment by Marto32** [comment]
I just recreated my venv and tried again and it does appear to be working as expected. Sorry for the false alarm!
