### ISSUE TITLE
Setuptools missing requirements.txt

### ISSUE THREAD

**Issue by limburgher** [dropbox/dropbox-sdk-python#331]
**Describe the bug**
setup.py depends on a requirements.txt file that is present in git but not in the 11.4.0 tarball.

**To Reproduce**
tar -xzf dropbox-11.4.0.tar.gz
cd dropbox-11.4.0
python3 setup.py build

**Expected Behavior**
Build completes, as it did for 11.3.0.

**Actual Behavior**
Traceback (most recent call last):
  File "/home/gwyn/fedora/git/python-dropbox/dropbox-11.4.0/setup.py", line 31, in <module>
    with open('requirements.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

**Screenshots**
N/A

**Versions**
11.4.0
3.9.2
Fedora 33

**Additional context**
I'm the Fedora python-dropbox package maintainer, so this blocks upgrading that RPM in Fedora.

**Comment by greg-db** [comment]
Thanks! I'll ask the team to fix that up.

**Comment by rogebrd** [comment]
This issue should be fixed in v11.4.1. Please let me know if this issue persists

**Comment by limburgher** [comment]
Looks great, thank you!

FYI, it might be nice to change the pytest-runner pin from ==5.2.0 to <=5.2.0; We have 4.0 on Fedora and it works just fine.
