### ISSUE TITLE
Replacement for team_reports_get_membership()

### ISSUE THREAD

**Issue by tristanlatr** [dropbox/dropbox-sdk-python#338]
**What is your question?**
I see that the method `DropboxTeam.team_reports_get_membership()` is deprecated and will be removed soon. I was wondering if there is any alternative calls that could get us the same infos ?

**Screenshots**
![Capture d’écran, le 2021-03-31 à 11 43 24](https://user-images.githubusercontent.com/19967168/113172320-5355cd80-9216-11eb-8f29-2e6fdb033f7b.png)

**Versions**
Latest version from github. 

**Additional context**
We are trying to retreive the list of accounts that are pending to join our team.

Thanks for you help :)

**Comment by greg-db** [comment]
There isn't an exact replacement for that deprecated method unfortunately.

If you want to list the accounts that are invited but not yet joined on your team though, you can use the [`team_members_list`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.DropboxTeam.team_members_list) and [`team_members_list_continue`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.DropboxTeam.team_members_list_continue) methods, and filter the results to members with [`TeamMemberStatus`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/team.html?highlight=TeamMemberInfo#dropbox.team.TeamMemberStatus)`.invited`.

**Comment by tristanlatr** [comment]
Thanks !
