### ISSUE TITLE
It is not possible list root folder's content

### ISSUE THREAD

**Issue by alfredocdmiranda** [dropbox/dropbox-sdk-python#34]
I am not sure if I am doing something wrong or if it is even possible to list root folder's content. After login when I try to user files_list_folder or files_get_metadata I got an error: 
ApiError: ListFolderError(u'path', LookupError(u'malformed_path', None))

I've tried to list other folders' content and it is working.

**Comment by andyCapone** [comment]
I was able to list the root folder's content by calling dbox.files_list_folder(""). What did you try?

**Comment by alfredocdmiranda** [comment]
Hey @andyCapone, thanks for your answer, I've tried dbox.files_list_folder("/"), dbox.files_list_folder(" "), dbox.files_list_folder("."). 

I didn't try your method...so, now it worked :D

Thanks again and sorry for this unecessary issue.

**Comment by andyCapone** [comment]
No problem! :-)
