### ISSUE TITLE
Output of dropbox.team.GetMembershipReport

### ISSUE THREAD

**Issue by angelaruiz0115** [dropbox/dropbox-sdk-python#343]
Hello, 

I am trying to use the Dropbox API to retrieve a list of Pending Members. The only method I can find to do this is the soon to be deprecated `dropbox.team.GetMembershipReport` which returns the following:

![Screen Shot 2021-04-13 at 11 01 02 AM](https://user-images.githubusercontent.com/9749784/114575223-f27fb980-9c47-11eb-847d-79bce3d2d371.png)

As you can see, the pending_invites field is NOT_SET which means I am unable to retrieve information about pending. Can you please tell me how I can remedy this, or possibly populate these fields?

Thank you.

**Comment by greg-db** [comment]
You can use [`team_members_list`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.DropboxTeam.team_members_list) and [`team_members_list_continue`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.DropboxTeam.team_members_list_continue) to list the members of a team and check if their status is [`TeamMemberStatus.invited`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/team.html#dropbox.team.TeamMemberStatus).

**Comment by angelaruiz0115** [comment]
Hi Greg, 

The methods `team_members_list` and `team_members_list_continue` do not show Members with Pending Requests, only member that have invited but not joined (i.e. the red circled area in the picture below). 

![Screen Shot 2021-04-13 at 1 31 27 PM](https://user-images.githubusercontent.com/9749784/114595990-097cd680-9c5d-11eb-962c-4fb45532a2d1.png)

I need the information in the purple. 

Thanks, 

Angela

**Comment by angelaruiz0115** [comment]
@greg-db please see my reply

**Comment by greg-db** [comment]
@angelaruiz0115 I see, thanks for clarifying. The API doesn't offer access to that list of members that have asked to join the team, as opposed to invitations, but I'll pass this along as a feature request. I can't promise if or when that might be implemented though.
