### ISSUE TITLE
finish_upload_session_finish_batch returns the wrong type

### ISSUE THREAD

**Issue by mgrivich** [dropbox/dropbox-sdk-python#347]
In the documentation for finish_upload_session_finish_batch at https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_upload_session_finish_batch the text says that the return type should be job_id, which can be used in files_upload_session_finish_batch_check. However, finish_upload_session_finish_batch actually returns UploadSessionFinishBatchLaunch, so I appear to have no way to run files_upload_session_finish_batch_check.

I've tried checking UploadSessionFinishBatchLaunch.is_complete(), but it always returns false.

My long term goal is to be able to do batched uploads, as uploading many small individual files is very slow.

My current code only attempts to do one file at a time:

         
    with stopwatch('upload %d bytes' % len(data)):
        try:
            
            session_start_result = dbx.files_upload_session_start(data, True)
            cursor = dropbox.files.UploadSessionCursor(session_start_result.session_id, len(data))
            commit = dropbox.files.CommitInfo(path, mode, client_modified=datetime.datetime(*time.gmtime(mtime)[:6]),mute=True)
            finish_arg = dropbox.files.UploadSessionFinishArg(cursor, commit)
            entries = []
            entries.append(finish_arg)

            finish_batch_result = dbx.files_upload_session_finish_batch(entries)
            
            #fails with  raise ValidationError("'%s' expected to be a string, got %s" stone.backends.python_rsrc.stone_validators.ValidationError: 'UploadSessionFinishBatchLaunch('async_job_id', 'dbjid:AAByrlt0cqBW4TSd0l3zacJwtfEoggGSgWqJfVFendyyaOjfSFfsCG-fofk96Rq4X1qOxNT3Qe-LJ0dwncFsRjTc')' expected to be a string, got dropbox.files.UploadSessionFinishBatchLaunch
            # check_result = dbx.files_upload_session_finish_batch_check(finish_batch_result)

            if(finish_batch_result.is_complete()):
                batch_result = finish_batch_result.get_complete()
                print('result: ', batch_result.entries[finish_arg])
            else:
               #always goes here, even if I wait, though the file does upload
                print('batch did not finish')

        except dropbox.exceptions.ApiError as err:
            print('*** API error', err)
            return None

I did find the javascript example for this task, but have been unable to port it. https://github.com/dropbox/dropbox-sdk-js/issues/80

**Comment by greg-db** [comment]
[The `UploadSessionFinishBatchLaunch` type](https://dropbox-sdk-python.readthedocs.io/en/latest/api/files.html#dropbox.files.UploadSessionFinishBatchLaunch) has a base of [`LaunchResultBase`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/async.html#dropbox.async_.LaunchResultBase), so you can use [`is_async_job_id`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/async.html#dropbox.async_.LaunchResultBase.is_async_job_id) and  [`get_async_job_id`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/async.html#dropbox.async_.LaunchResultBase.get_async_job_id) to check for and get the job ID. You should use that ID to call [`files_upload_session_finish_batch_check`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_upload_session_finish_batch_check) to check the status of the job.

Also, your `finish_batch_result` is only set when you call `files_upload_session_finish_batch`, and won't automatically change once retrieved. You'll need to poll [`files_upload_session_finish_batch_check`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_upload_session_finish_batch_check) to see when the job is done.

**Comment by mgrivich** [comment]
Thanks. I asked a follow up in a new issue because it is a different question.
