### ISSUE TITLE
Batch uploading gives no performance improvement

### ISSUE THREAD

**Issue by mgrivich** [dropbox/dropbox-sdk-python#348]
I've gotten batch uploading working in python, but it is not improving performance. Specifically, dbx.files_upload_session_start() takes 100 - 600 ms for each tiny file. This the case for dbx.files_upload_session_start(data, True) and dbx.files_upload_session_start(None, False, dropbox.files.UploadSessionType.concurrent). Am I doing something wrong, or are concurrent uploads not implemented for Python? I could wrap Dropbox functions in Python ThreadPools as described here: https://stackoverflow.com/questions/2846653/how-can-i-use-threading-in-python, but at that point I'm not sure that batching gets me anything of value.

My code is below. Queue_for_upload is done for each file, and then finish_upload is done after many files.

    def queue_for_upload(dbx, fullname, folder, subfolder, name, overwrite=False):
      print('queue for upload')
    
      global uploading_entries
    
      path = '/%s/%s/%s' % (folder, subfolder.replace(os.path.sep, '/'), name)
      while '//' in path:
          path = path.replace('//', '/')
      mode = (dropbox.files.WriteMode.overwrite
              if overwrite
              else dropbox.files.WriteMode.add)
      mtime = os.path.getmtime(fullname)
      with open(fullname, 'rb') as f:
          data = f.read()
      
      with stopwatch('upload %d bytes' % len(data)):
          try:
              session_start_result = dbx.files_upload_session_start(data, True)

              #also slow
              #session_start_result = dbx.files_upload_session_start(None, False, dropbox.files.UploadSessionType.concurrent)
            
              cursor = dropbox.files.UploadSessionCursor(session_start_result.session_id, len(data))
              commit = dropbox.files.CommitInfo(path, mode, client_modified=datetime.datetime(*time.gmtime(mtime)[:6]),mute=True)
              finish_arg = dropbox.files.UploadSessionFinishArg(cursor, commit)
              uploading_entries.append(finish_arg)
          except dropbox.exceptions.ApiError as err:
              print('*** API error', err)
 
    def finish_upload(dbx):
      global uploading_entries
      try:
        
          finish_batch_result = dbx.files_upload_session_finish_batch(uploading_entries)
        
          if(finish_batch_result.is_async_job_id()):

              check_result = dbx.files_upload_session_finish_batch_check(finish_batch_result.get_async_job_id())
              while(check_result.is_in_progress()):
                  print('in progress')
                  time.sleep(0.1)
                  check_result = dbx.files_upload_session_finish_batch_check(finish_batch_result.get_async_job_id())
                
              if(check_result.is_complete()):
                  print('complete')
                  batch_result_list = check_result.get_complete().entries
                  for result in batch_result_list:
                      print('succeeded: ', result.is_success())
                
              elif(check_result.is_internal_error()):
                  print('internal error')
              elif(check_result.is_invalid_async_job_id()):
                  print('invalid async job')
              elif(check_result.is_other()):
                  print('is other')
        
          else:
              print('not async')

      except dropbox.exceptions.ApiError as err:
          print('*** API error', err)
          return None

      uploading_entries = []

    @contextlib.contextmanager
    def stopwatch(message):
        """Context manager to print how long a block of code took."""
        t0 = time.time()
        try:
            yield
        finally:
            t1 = time.time()
            print('Total elapsed time for %s: %.3f' % (message, t1 - t0))

**Comment by greg-db** [comment]
You could use the concurrent session type by using `UploadSessionType.concurrent` as you mentioned, but it's not something that happens automatically; it's something you'd need to make use of by uploading multiple chunks of a single file in parallel. That's only useful for larger files though, where you break each file into multiple chunks.

For uploading multiple small files like this, you should perform the `files_upload_session_start` calls in parallel, and then use `files_upload_session_finish_batch` to commit them together in batch. Performing `files_upload_session_start` in parallel will increase overall throughput, and using `files_upload_session_finish_batch` helps avoid lock contention.

I recommend reading [the Performance Guide](https://developers.dropbox.com/dbx-performance-guide) for more information.

**Comment by mgrivich** [comment]
Thanks. Here is my corrected code. It works well for uploading many small files.

    """"
    Modified from:
    https://github.com/dropbox/dropbox-sdk-python/blob/master/example/updown.py

    Fixed issue where remote directory list would fail for too many files
    Implemented batch uploading to improve speed
    Removed download functionality
    """"
    
    from __future__ import print_function

    import subprocess
    import sys
    import argparse
    import contextlib
    import datetime
    import os
    try:
        import six
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", 'six'])
    finally:
        import six

    import sys
    import time
    import unicodedata
    import webbrowser
    import platform

    from dropbox import DropboxOAuth2FlowNoRedirect
    from multiprocessing.dummy import Pool
    from functools import partial

    if sys.version.startswith('2'):
        input = raw_input  # noqa: E501,F821; pylint: disable=redefined-builtin,undefined-variable,useless-suppression
    try:
        import dropbox
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", 'dropbox'])
    finally:
        import dropbox


    parser = argparse.ArgumentParser(description='Upload given path to Dropbox')
    parser.add_argument('local_directory', help='Local directory to upload')

    class Upload_parameters:
        def __init__(self,fullname, folder, subfolder, name, size, overwrite):
            self.fullname = fullname
            self.folder = folder
            self.subfolder = subfolder
            self.name = name
            self.size = size
            self.overwrite = overwrite

    class Counts:
        def __init__(self):     
            self.pre_existing = 0
            self.uploaded = 0
            self.failed = 0     

    def main():
     
        """Main program.

        Parse command line, then iterate over files and directories under
        rootdir and upload all files.  Skips some temporary files and
        directories, and avoids duplicate uploads by comparing size and
        mtime with the server.
        """
        args = parser.parse_args()

        folder = "dropbox/upload/path/" + platform.node() #upload to a folder with current computer name
        rootdir = os.path.expanduser(args.local_directory)
        print('Dropbox folder name:', folder)
        print('Local directory:', rootdir)      
        
        if not os.path.exists(rootdir):
            print(rootdir, 'does not exist on your filesystem')
            sys.exit(1)
        elif not os.path.isdir(rootdir):
            print(rootdir, 'is not a folder on your filesystem')
            sys.exit(1)

        APP_KEY = "PUT_APP_KEY_HERE"

        auth_flow = DropboxOAuth2FlowNoRedirect(APP_KEY, use_pkce=True, token_access_type='offline')

        authorize_url = auth_flow.start()
        print("1. Go to (it should open automatically): " + authorize_url)
        print("2. Click \"Allow\" (you might have to log in first).")
        print("3. Copy the authorization code.")
        webbrowser.open(authorize_url)
        auth_code = input("Enter the authorization code here: ").strip()

        try:
            oauth_result = auth_flow.finish(auth_code)
        except Exception as e:
            print('Error: %s' % (e,))
            exit(1)

        dbx = dropbox.Dropbox(oauth2_refresh_token=oauth_result.refresh_token, app_key=APP_KEY)
                      

        files_per_upload = 100
        maximum_size = 25000000 #MB
        
        counts = Counts()
        
        upload_parameters = []
        total_size = 0
        
        for dn, dirs, files in os.walk(rootdir):
            subfolder = dn[len(rootdir):].strip(os.path.sep)
            listing = list_folder(dbx, folder, subfolder)
            print('Descending into ', subfolder)
            
            

            # First do all the files.
            for name in files:
                fullname = os.path.join(dn, name)
                size = os.path.getsize(fullname)
                
                if(size >= maximum_size):
                    print('Large file uploads not implemented. Dropbox requires special procedures for large files. ', filename , ' is too large.')
                    counts.failed = counts.failed + 1
                    continue
           
                if not isinstance(name, six.text_type):
                    name = name.decode('utf-8')
                nname = unicodedata.normalize('NFC', name)
                
                if name.startswith('.'):
                    print('Skipping dot file:', name)
                elif name.startswith('@') or name.endswith('~'):
                    print('Skipping temporary file:', name)
                elif name.endswith('.pyc') or name.endswith('.pyo'):
                    print('Skipping generated file:', name)
                elif nname in listing:
                    md = listing[name]
                    mtime = os.path.getmtime(fullname)
                    mtime_dt = datetime.datetime(*time.gmtime(mtime)[:6])
                   
                    if (isinstance(md, dropbox.files.FileMetadata) and
                            mtime_dt == md.client_modified and size == md.size):
                        counts.pre_existing = counts.pre_existing + 1
                        print(name, 'is already synced [stats match]')
                    else:
                        print(name, 'has changed since last sync')
                        
                        if(len(upload_parameters) >= files_per_upload or total_size + size >= maximum_size):
                            counts = upload_batch(dbx, upload_parameters, counts)
                            upload_parameters = []
                            total_size = 0
                        
                        
                        total_size = size + total_size
                        upload_parameters.append(Upload_parameters(fullname, folder, subfolder, name, size, True))  
                            
                else:
                    print('Uploading: ', name)
                    
                    if(len(upload_parameters) >= files_per_upload or total_size + size >= maximum_size):
                        counts = upload_batch(dbx, upload_parameters, counts)
                        upload_parameters = []
                        total_size = 0
                    
                    total_size = size + total_size
                    upload_parameters.append(Upload_parameters(fullname, folder, subfolder, name, size, True))                      


            # Then choose which subdirectories to traverse.
            keep = []
            for name in dirs:
                if name.startswith('.'):
                    print('Skipping dot directory:', name)
                elif name.startswith('@') or name.endswith('~'):
                    print('Skipping temporary directory:', name)
                elif name == '__pycache__':
                    print('Skipping generated directory:', name)
                else:
                    print('Descending into: ', name)
                    keep.append(name)

            dirs[:] = keep
            
        if(len(upload_parameters) > 0):
            counts = upload_batch(dbx, upload_parameters, counts)
            upload_parameters = []  
            total_size = 0        

        dbx.close()

        print('')
        print('Previously uploaded files: ', counts.pre_existing)
        print('New files uploaded: ', counts.uploaded)
        print('Failed uploads: ', counts.failed)
        print('Finished Uploading')
        print('')
        print('')
          

    def list_folder(dbx, folder, subfolder):
        """List a folder.

        Return a dict mapping unicode filenames to
        FileMetadata|FolderMetadata entries.
        """
        path = '/%s/%s' % (folder, subfolder.replace(os.path.sep, '/'))
        while '//' in path:
            path = path.replace('//', '/')
        path = path.rstrip('/')
        
        rv = {}
        
        try:
            result = dbx.files_list_folder(path)
        except dropbox.exceptions.ApiError as err:
            rv = {} #Folder not found on remote
        else:
            for entry in result.entries:
                if isinstance(entry, dropbox.files.FileMetadata):
                    rv[entry.name] = entry
        
            while result.has_more:
                result = dbx.files_list_folder_continue(result.cursor)
            
                for entry in result.entries:
                    if isinstance(entry, dropbox.files.FileMetadata):
                        rv[entry.name] = entry            
        return rv

       
    def start_upload(upload_parameters, dbx):
        """ Start the uploading of a single file. 

        Return the uploading_entry, or None in case of error.
        """
        fullname = upload_parameters.fullname
        folder = upload_parameters.folder
        subfolder = upload_parameters.subfolder
        name = upload_parameters.name
        size = upload_parameters.size
        overwrite = upload_parameters.overwrite
        
        path = '/%s/%s/%s' % (folder, subfolder.replace(os.path.sep, '/'), name)
        while '//' in path:
            path = path.replace('//', '/')
        mode = (dropbox.files.WriteMode.overwrite
                if overwrite
                else dropbox.files.WriteMode.add)
        mtime = os.path.getmtime(fullname)
        with open(fullname, 'rb') as f:
            data = f.read()
          
        try:
            session_start_result = dbx.files_upload_session_start(data, True)
            
            cursor = dropbox.files.UploadSessionCursor(session_start_result.session_id, len(data))
            commit = dropbox.files.CommitInfo(path, mode, client_modified=datetime.datetime(*time.gmtime(mtime)[:6]),mute=True)
            uploading_entry = dropbox.files.UploadSessionFinishArg(cursor, commit)
            return uploading_entry
            
        except dropbox.exceptions.ApiError as err:
            print('*** API error', err)
        
        return None
       

    def upload_batch(dbx, upload_parameters, counts):
        """ Finish the uploading of a batch of files

        """
        size = 0
        for upload_params in upload_parameters:
            size = size + upload_params.size
            
        with stopwatch('upload %d bytes' % size):
            pool = Pool(len(upload_parameters))
            start_upload_partial = partial(start_upload, dbx=dbx)
            uploading_entries = pool.map(start_upload_partial, upload_parameters)
            
            try:
               
                finish_batch_result = dbx.files_upload_session_finish_batch(uploading_entries)
                
                if(finish_batch_result.is_async_job_id()):

                    check_result = dbx.files_upload_session_finish_batch_check(finish_batch_result.get_async_job_id())
                    while(check_result.is_in_progress()):
                        time.sleep(0.1)
                        check_result = dbx.files_upload_session_finish_batch_check(finish_batch_result.get_async_job_id())
                        
                    if(check_result.is_complete()):
                        batch_result_list = check_result.get_complete().entries
                        for result in batch_result_list:
                            if(result.is_success()):
                                counts.uploaded = counts.uploaded + 1
                               # print('Upload succeeded')
                            else:
                                counts.failed = counts.failed + 1
                                print('Upload failed')
                        
                    elif(check_result.is_internal_error()):
                        counts.failed = counts.failed + 1
                    elif(check_result.is_invalid_async_job_id()):
                        counts.failed = counts.failed + 1
                    elif(check_result.is_other()):
                        counts.failed = counts.failed + 1
                
                else:
                    print('Not Async. Programmer Error.')
                    exit()

            except dropbox.exceptions.ApiError as err:
                print('*** API error', err)

        return counts

    def upload(dbx, fullname, folder, subfolder, name, overwrite=False):
        """Upload a single file. Slow, especially for small files.

        Return the request response, or None in case of error.
        """
        path = '/%s/%s/%s' % (folder, subfolder.replace(os.path.sep, '/'), name)
        while '//' in path:
            path = path.replace('//', '/')
        mode = (dropbox.files.WriteMode.overwrite
                if overwrite
                else dropbox.files.WriteMode.add)
        mtime = os.path.getmtime(fullname)
        with open(fullname, 'rb') as f:
            data = f.read()
        with stopwatch('upload %d bytes' % len(data)):
            try:
                res = dbx.files_upload(
                    data, path, mode,
                    client_modified=datetime.datetime(*time.gmtime(mtime)[:6]),
                    mute=True)
            except dropbox.exceptions.ApiError as err:
                print('*** API error', err)
                return None
        print('uploaded as', res.name.encode('utf8'))
        return res


    @contextlib.contextmanager
    def stopwatch(message):
        """Context manager to print how long a block of code took."""
        t0 = time.time()
        try:
            yield
        finally:
            t1 = time.time()
            print('Total elapsed time for %s: %.3f' % (message, t1 - t0))

    if __name__ == '__main__':
        main()
