### ISSUE TITLE
Feature Request: checksum attribute

### ISSUE THREAD

**Issue by kg-2** [dropbox/dropbox-sdk-python#36]
Maybe I missed it somewhere in the docs, but is it possible to access the checksum values of the stored files on the server? I've found the rev attribute but that is only useful after I've downloaded and hashed the file at least once. Is there a way to compare the values of remote files to local files without first downloading them? Thanks for the awesome product and your continued work.

**Comment by braincore** [comment]
Unfortunately, this has been long requested, and we don't have any immediate plans of exposing a checksum. If we did this, it would be something a bit more complicated than the SHA-1 hash of the file.

**Comment by kg-2** [comment]
yeah it would be nice if there was a way to compare files without having to download a local copy.

**Comment by dtheodor** [comment]
> If we did this, it would be something a bit more complicated than the SHA-1 hash of the file.

Why? A sha1 or equivalent is what people are requesting, which you probably already store. Not something more complicated.

**Comment by greg-db** [comment]
I believe that was in reference to the specifics of the Dropbox backend implementation which wouldn't make a simple SHA-1 the most likely candidate.

**Comment by greg-db** [comment]
The Dropbox API now offers a hash of file data that you can use to verify a file's contents. It isn't a single MD5 or SHA1, but rather a combination of SHA256 hashes of the pieces of the file. You can find it in the Python SDK as [`FileMetadata.content_hash`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.files.FileMetadata.content_hash).

You can find more information here:

https://www.dropbox.com/developers/reference/content-hash
