### ISSUE TITLE
HTTP errors during `refresh_access_token` calls are not converted to SDK errors

### ISSUE THREAD

**Issue by samschott** [dropbox/dropbox-sdk-python#360]
**Describe the bug**
When the Dropbox SDK refreshes the access token with `Dropbox.refresh_access_token()`, resulting HTTP errors are sometimes not converted to the appropriate SDK error. At the moment, only 400 errors are converted to a `AuthError`:

https://github.com/dropbox/dropbox-sdk-python/blob/d81a2342be0b5bf2629fdcecd4fba3a8cc9cc2f7/dropbox/dropbox_client.py#L402-L407

**Expected Behavior**
Other errors should be converted to SDK error types as appropriate before being raised. For example,  errors with status >= 500 should be raised as `InternalServerError`.

**Actual Behavior**
Attempting to refresh an auth token raised a `requests.HTTPError` with status 503 instead of an `InternalServerError` while Dropbox servers where undergoing scheduled maintenance on 22 May 2021.

**Versions**
* What version of the SDK are you using? 11.9.0
* What version of the language are you using? Python 3.9.1

**Comment by greg-db** [comment]
Thanks! I'll ask the team to fix this up.

**Comment by greg-db** [comment]
This should be fixed in v11.26.0.

**Comment by samschott** [comment]
Thanks!
