### ISSUE TITLE
Wrong content-type returned by files_list_folder_longpoll, "text/plain" instead of "application/json"

### ISSUE THREAD

**Issue by rrerolle** [dropbox/dropbox-sdk-python#38]
The following sample code:

```python
#!/usr/bin/python
import dropbox, os
dbx = dropbox.Dropbox(os.environ['DROPBOX_TOKEN'])
root = dbx.files_list_folder('')
print dbx.files_list_folder_longpoll(root.cursor, timeout=30)
```
returns:

    Traceback (most recent call last):
      File "longpoll_test.py", line 7, in <module>
        print dbx.files_list_folder_longpoll(root.cursor, timeout=30)
      File "/home/rrerolle/Workspace/Code/rembox/venv/local/lib/python2.7/site-packages/dropbox/base.py", line 89, in files_list_folder_longpoll
        None)
      File "/home/rrerolle/Workspace/Code/rembox/venv/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 175, in request
        request_binary)
      File "/home/rrerolle/Workspace/Code/rembox/venv/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 256, in request_json_string_with_retry
        request_binary)
      File "/home/rrerolle/Workspace/Code/rembox/venv/local/lib/python2.7/site-packages/dropbox/dropbox.py", line 337, in request_json_string
        r.headers.get('content-type'))
    AssertionError: Expected content-type to be application/json, got 'text/plain'

It appears the request succeeds, but returns a "text/plain" content-type, while the dropbox v2 client explicitly expects "application/json", as demonstrated in https://github.com/dropbox/dropbox-sdk-python/blob/002e6df32a6c9446554f6f53b2510d284adc9943/dropbox/dropbox.py#L335-L337

This is probably an overlook in the v2 API server itself so I'm not sure there is anything to do client wise. Still, for now, using it requires either catching the AssertionError, or running python with -O to disable the asserts.

**Comment by braincore** [comment]
Thanks for the report. This is a known issue, and a fix is currently being worked on. I'll update the thread once it's complete.

**Comment by elnerdo** [comment]
Any progress yet?

**Comment by braincore** [comment]
Thank you for your patience. This has finally been fixed server-side and will not require any SDK updates.

**Comment by Laski** [comment]
Any ETA for deploy? This is still biting me.

**Comment by mhubig** [comment]
Sorry problem's still not fixed here!

**Comment by braincore** [comment]
Thanks for letting us know. You are all correct. When no change has been made to a user's Dropbox, the content-type is still text/plain. The fix will be in in the next day.

**Comment by braincore** [comment]
It's fixed!

**Comment by Laski** [comment]
Thank you!
