### ISSUE TITLE
I shared two different folders to two differnent clients but my webhook received same users and accounts

### ISSUE THREAD

**Issue by johnny-cy** [dropbox/dropbox-sdk-python#387]
I attempt to create two different shared folders for two clients and I suppose to received two different onchange notification from provided webhook so I go to dropbox/developer and create one app named 'the_testapp' and generate a access token let's call it 'the_token' and give it a webbhook endpoint to receive on change notification. after then I create two shared folders for user_1 and user_2. ( eg: shared_folder_1 for user_1 and shared_folder_2 for user_2) 

I think everything is ready now so I start to monitor those two folders via webook, but what request.data I received from the webhook for these two clients are seemingly identical, user_1 and user_2 uploaded a file to shared_folder_1 and shared_folder_2  respectively, would it be corrected I expect to receive different value for delta.users or list_folder.accounts ?

![Screen Shot 2021-09-26 at 9 42 16 AM](https://user-images.githubusercontent.com/54311452/134790339-763ca6cf-2160-425e-83a2-e809e043f908.png)

Thanks for reading this and any advise would be appreciated

**Comment by greg-db** [comment]
This is the expected result in this case. Dropbox webhooks notifications are sent for any changes (shared or not) in the account(s) that are connected to the app. In your case, you connected one account to the app (by generating an access token). Then, for each change in that account, a webhook notification is sent. It doesn't matter who made any particular change, but rather that there is change in the connected account.

You would need to connect the other account to the app as well (e.g., via [the OAuth app authorization flow](https://developers.dropbox.com/oauth-guide)) to get notifications of changes in that other account as well.
