### ISSUE TITLE
Limiting retries due to rate-limited requests, and determining the suggested backoff.

### ISSUE THREAD

**Issue by vinodc** [dropbox/dropbox-sdk-python#39]
It would be preferable to avoid the potential infinite loop here on 429 errors: https://github.com/dropbox/dropbox-sdk-python/blob/002e6df32a6c9446554f6f53b2510d284adc9943/dropbox/dropbox.py#L259
Could there be some mechanism to separately control the number of retries for rate-limited requests? I would prefer our implementation to retry on 5** errors, but immediately fail on 429 errors providing me with an option on when to retry based on the Retry-After header in the response.

I believe this would also require the TODO item at https://github.com/dropbox/dropbox-sdk-python/blob/002e6df32a6c9446554f6f53b2510d284adc9943/dropbox/dropbox.py#L329 to be implemented, storing the backoff value based on the Retry-After header, unless I'm mistaken.

**Comment by braincore** [comment]
Hi @vinodc, would you want the SDK to fail out on the first 429, or retry a few times? We could consider adding a flag to adjust how the SDK handles 429s.

**Comment by vinodc** [comment]
@braincore Personally, I'd want it to fail and raise the error on the first 429, as I already have custom logic to handle the retries myself. I agree that an option that adjusts the number of 429s permissable in a row would be most flexible.

**Comment by braincore** [comment]
A new parameter, `max_retries_on_rate_limit`, has been introduced. You can set it to zero to eliminate automatic retrying on 429s: http://dropbox-sdk-python.readthedocs.org/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.__init__

**Comment by vinodc** [comment]
Thanks @braincore!
