### ISSUE TITLE
Not compatible with 3.4

### ISSUE THREAD

**Issue by jghancock** [dropbox/dropbox-sdk-python#4]
Lines 47 and 48:
 args = parser.parse_args()
    if sum([bool(b) for b in args.yes, args.no, args.default]) > 1:

Pycharm is telling me that:
"Python 3.4 does not support this syntax in list comprehensions"

**Comment by braincore** [comment]
The `updown.py` example has been made fully-PY3 compatible in the latest release on GitHub and PyPI. Thanks!
