### ISSUE TITLE
files_get_metadata result does not include sharing_info

### ISSUE THREAD

**Issue by mispy** [dropbox/dropbox-sdk-python#40]
I'm getting a discrepancy between the curl result for files/get_metadata and the Python object returned by files_get_metadata for a file in a shared folder. Specifically, the sharing_info field is not present and so I cannot access modified_by.

**Comment by braincore** [comment]
We've updated the Python SDK. You can find the `sharing_info` field in the `FileMetadata` response object: http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.files.FileMetadata

**Comment by mispy** [comment]
Thanks! :+1:
