### ISSUE TITLE
download

### ISSUE THREAD

**Issue by alicera** [dropbox/dropbox-sdk-python#402]
```
git clone https://github.com/dropbox/dropbox-sdk-python
cd dropbox-sdk-python/example
python updown.py
```
```
Create an app via the
https://www.dropbox.com/developers/apps/
```
how to use download
I can upload with the py

**Comment by greg-db** [comment]
You can download a file using [`files_download`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_download) or [`files_download_to_file`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_download_to_file). You can find examples [here](https://github.com/dropbox/dropbox-sdk-python/blob/main/example/updown.py#L159) and [here](https://github.com/dropbox/dropbox-sdk-python/blob/main/example/back-up-and-restore/backup-and-restore-example.py#L55).

You can also use [`files_download_zip`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_download_zip) to download an entire folder as a zip.

**Comment by alicera** [comment]
I already run the updown.py.
But it exe upload.
How to trigger the download behave?

**Comment by greg-db** [comment]
I'm afraid I don't understand your message. The updown.py example performs a number of different operations as an example of how to use the API. For your own purposes, you'll need to write code to perform exactly the operations you want, for instance using the download methods I linked to in my previous message. 

If something isn't working as expected with any of the API methods, please share the code you have written and show what isn't working (e.g., show the unexpected error or output).

**Comment by alicera** [comment]
https://github.com/dropbox/dropbox-sdk-python/blob/main/example/updown.py

I put a file to /data/1.jpg in the dropbox.
If I want to download 1.jpg, how can I command for the updown.py ?

**Comment by greg-db** [comment]
If you are trying to write your own code to download a file, you should use [`files_download`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_download) or [`files_download_to_file`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.Dropbox.files_download_to_file).

If you are just trying to use the updown.py example, you can run it with the `--help` flag for usage information.

**Comment by alicera** [comment]
Thanks
