### ISSUE TITLE
warning from setuptools

### ISSUE THREAD

**Issue by ceamac** [dropbox/dropbox-sdk-python#409]
**Describe the bug**
setuptools gives this warning:
`UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead`

**Versions**
* What version of the SDK are you using?  *11.26.0*
* What version of the language are you using?  *3.9.9*
* What platform are you using? *Linux*

**Comment by greg-db** [comment]
Thanks! I'll ask the team to fix that up.
