### ISSUE TITLE
Make sure HTTP 400 error message body is shown by default.

### ISSUE THREAD

**Issue by cakoose** [dropbox/dropbox-sdk-python#42]
In #33, someone got an HTTP 400 exception and didn't know what to do.

The Dropbox server usually puts useful information in HTTP 400 error responses.  If that error message were surfaced by default (i.e. visible in the stack trace) the issue might have been easier to resolve.

**Comment by dalanmiller** [comment]
Weirdly it's just the OAuth2 `.finish()` attempt that does this, the previous messages explain what is going wrong such as when you're missing `client_id` in your redirect to the Dropbox OAuth request endpoint.

**Comment by dalanmiller** [comment]
Anyway I can get this right now @cakoose ?

**Comment by cakoose** [comment]
I don't have time to try this out, but maybe copy [this snippet](https://github.com/dropbox/dropbox-sdk-python/blob/002e6df32a6c9446554f6f53b2510d284adc9943/dropbox/dropbox.py#L319) over to [here](https://github.com/dropbox/dropbox-sdk-python/blob/713357589efa5361d6a7c6497a2423b2777f95d3/dropbox/oauth.py#L60)?

If that works, can you send a pull request?

**Comment by rogebrd** [comment]
This seems to be fixed and out of date.  The OAuth2 flow now puts useful information regarding the cause of 400 in the response.
