### ISSUE TITLE
Version number not set on 11.30.0 tag

### ISSUE THREAD

**Issue by SFrijters** [dropbox/dropbox-sdk-python#425]
**Describe the bug**

In the 11.29.0 tag, the `__version__` is set in https://github.com/dropbox/dropbox-sdk-python/blob/v11.29.0/dropbox/dropbox_client.py

But for 11.30.0 it is not: https://github.com/dropbox/dropbox-sdk-python/blob/v11.30.0/dropbox/dropbox_client.py

Is this intended?

**Expected Behavior**

Each tagged version has the `__version__` set in `dropbox/dropbox_client.py`.

**Comment by greg-db** [comment]
Thanks for the note! I'll ask the team to fix that up.

**Comment by greg-db** [comment]
This is fixed now. Thanks again!
