### ISSUE TITLE
InternalServerError when trying to upload with updown.py

### ISSUE THREAD

**Issue by jbiswas** [dropbox/dropbox-sdk-python#43]
I am trying to use [updown.py](https://github.com/dropbox/dropbox-sdk-python/blob/8a471c15816dff310e8beaa636123259488a939b/example/updown.py) to upload the contents of a local subfolder to my dropbox and I keep getting this exception:
```
$ python updown.py --token MYTOKEN /Dropbox/path local/relative/path
Dropbox folder name: /Dropbox/path
Local directory: local/relative/path
Total elapsed time for list_folder: 1.146
Descending into  ...
file010.bin is already synced [stats match]
file008.bin is already synced [stats match]
file007.bin is already synced [stats match]
Upload file003.bin? [Y/n]
Total elapsed time for upload 3974 bytes: 26.167
Traceback (most recent call last):
  File "updown.py", line 247, in <module>
    main()
  File "updown.py", line 108, in main
    upload(dbx, fullname, folder, subfolder, name)
  File "updown.py", line 185, in upload
    mute=True)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/base.py", line 393, in files_upload
    f)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 175, in request
    request_binary)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 256, in request_json_string_with_retry
    request_binary)
  File "/usr/local/lib/python2.7/dist-packages/dropbox/dropbox.py", line 320, in request_json_string
    raise InternalServerError(r.status_code, r.text)
dropbox.exceptions.InternalServerError
```
In `local/relative/path` I have several random binary files. As you can see in the output despite the exception the files seem to be uploaded correctly. In this case I am running the script the fourth time. Is there something I need to check for myself? Or is there really an InternalServerError?

**Comment by braincore** [comment]
Hi @jbiswas,

Could you fill out https://www.dropbox.com/developers/contact so we can look up the relevant information for your account?

**Comment by braincore** [comment]
Oh, and please include the `account_id` in the contact form if it's for a specific user and not your own account.

**Comment by jbiswas** [comment]
@braincore thanks for the reply. I have filled the form and it is for my account.

**Comment by braincore** [comment]
We have a fix already on its way. It should go live by tomorrow evening Pacific Time.

**Comment by jbiswas** [comment]
Wow that's great. Thanks a lot.

**Comment by braincore** [comment]
Thanks again for the report. The bug is resolved. Please re-open the issue if the problem persists.
