### ISSUE TITLE
Query for rate limit on Dropbox Business / Teams account via Python SDK?

### ISSUE THREAD

**Issue by luckman212** [dropbox/dropbox-sdk-python#449]
Is it possible to query for the current # of API calls (and API limit) a Dbx Advanced/Teams account has made within the month?

**Versions**
* SDK: 11.35.0
* Python 3.10
* macOS

**Comment by greg-db** [comment]
The Dropbox API doesn't offer a way to query a team's currently monthly [data transport](https://www.dropbox.com/developers/reference/data-transport-limit) limit usage, but I'll pass this along as a feature request. I can't promise if or when that might be implemented though. You can query the team's data transport limit itself though, using [`team_features_get_values`](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html#dropbox.dropbox_client.DropboxTeam.team_features_get_values), like this:
```python
dbx = dropbox.DropboxTeam(ACCESS_TOKEN)

print(dbx.team_features_get_values(features=[dropbox.team.Feature.upload_api_rate_limit]))
```

(Note that this is unrelated to the general rate limiting system that applies to all account types and operates on much shorter time scales. It is not possible to query the usages/limits for that general system.)

**Comment by luckman212** [comment]
Ok thanks @greg-db 

Actually it's the latter (the short term rate limiting system) data that I was after, I was hoping to have a way to check when our account was being rate-limited. Is there a reason that data is not exposed anywhere?
