### ISSUE TITLE
DropboxOAuth2Flow.start() produces incorrect URL on Python 3

### ISSUE THREAD

**Issue by BlaXpirit** [dropbox/dropbox-sdk-python#45]
dropbox.DropboxOAuth2Flow(
        APP_KEY, APP_SECRET,
        redirect_uri, session, 'dropbox-auth-csrf-token'
    ).start()

This code returns:

[https://www.dropbox.com/1/oauth2/authorize?redirect_uri=http://localhost:5000/dropbox-auth-finish&response_type=code&client_id=REDACTED&state=b'REDACTED'](https://www.dropbox.com/1/oauth2/authorize?redirect_uri=http://localhost:5000/dropbox-auth-finish&response_type=code&client_id=REDACTED&state=b'REDACTED')

Notice that at the end this contains a representation of a bytestring, which is invalid.

Consequently:

    dropbox.oauth.CsrfException: expected b'REDACTED', got "b'REDACTED'"

**Comment by braincore** [comment]
Thanks for the report! This has been fixed in release 5.2.1.
