### ISSUE TITLE
files_search_v2 returns File Metadata with server_modified set to a random client_modified value

### ISSUE THREAD

**Issue by jporcenaluk** [dropbox/dropbox-sdk-python#460]
**Describe the bug**
When searching for files using the `files_search_v2` function, the metadata for the files includes a repeated value for `server_modified` that is randomly retrieved from any one of the files' `client_modified` field values.

This makes it very difficult to know if a file needs to be downloaded, as `client_modified` is [called out in the docs](https://dropbox-sdk-python.readthedocs.io/en/latest/api/files.html#dropbox.files.FileMetadata) as _not_ a reliable way to find that out, where `server_modified` is intended to be. Current functionality indicates that `server_modified` is _not_ reliable for that purpose.

**To Reproduce**
1. Upload two files to dropbox at different times
2. Use [files_search_v2](https://dropbox-sdk-python.readthedocs.io/en/latest/api/dropbox.html?highlight=files_search_v2#dropbox.dropbox_client.Dropbox.files_search_v2) to retrieve files
2. Print the `client_modified` and `server_modified` metadata on the files
3. Observe that `client_modified` is different for each file, but `server_modified` is the same for each file (and is set to one or the other of the `client_modified` values) 

**Example Code**
```
from datetime import datetime, timedelta
import pytz
import dropbox as dropbox
from dropbox.files import SearchOptions

data = {
  "dropboxFolder": "/a_folder",
  "ticketingToken": "abcd",
  "timeZone": "Europe/London"
}

dbx = dropbox.Dropbox(data["ticketingToken"])
time_zone = data["timeZone"]
dropbox_dir = data["dropboxFolder"]
datetime_now = datetime.now(tz=pytz.timezone(time_zone))
current_month_strftime = datetime_now.strftime("%Y %m")

files = dbx.files_search_v2(
        query=current_month_strftime, options=SearchOptions(path=dropbox_dir)
    ).matches

for idx, file in enumerate(files):
    file = file.metadata.get_metadata()
    print(f"file_{idx}"," - ", file.client_modified," - ", file.server_modified)
```

**Expected Behavior**
Expected to see `server_modified` has different values per file that indicate when they were last modified.

**Actual Behavior**
`server_modified` is the same value for each file, and randomly changes, and is aligned with _one_ random `client_modified` value from what is returned from the search.

**Screenshots**
<img width="669" alt="image" src="https://user-images.githubusercontent.com/4012781/214365733-8004a6aa-0e3c-4523-a04d-94112911878f.png">

**Versions**
* What version of the SDK are you using?
11.36.0
* What version of the language are you using?
Python 3.9
* What platform are you using? (if applicable)
OSX

**Additional context**
This is important to us, as we require a reliable way to identify new files being uploaded to Dropbox for our use case.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it and I'll follow up here once I have an update.

**Comment by jporcenaluk** [comment]
Thanks @greg-db ! I updated the ticket with example code that should work once the following dependencies are installed:

```
dropbox
pytz
```

**Comment by greg-db** [comment]
Apologies for the delayed response. The team has reported that this was fixed. Please let us know if you're still seeing this.
