### ISSUE TITLE
Version number not set on 11.36.1 tag

### ISSUE THREAD

**Issue by SFrijters** [dropbox/dropbox-sdk-python#465]
**Describe the bug**

In the 11.36.0 tag, the `__version__` is set in https://github.com/dropbox/dropbox-sdk-python/blob/v11.36.0/dropbox/dropbox_client.py

But for 11.36.1 it is not: https://github.com/dropbox/dropbox-sdk-python/blob/v11.36.1/dropbox/dropbox_client.py

Cf. https://github.com/dropbox/dropbox-sdk-python/issues/425

**Expected Behavior**

Each tagged version has the `__version__` set in dropbox/dropbox_client.py.

**Comment by greg-db** [comment]
Thanks for letting us know! I'll ask the team to get that fixed up.
