### ISSUE TITLE
v11.36.1 not available on pypi

### ISSUE THREAD

**Issue by trollwookiee** [dropbox/dropbox-sdk-python#469]
Only dropbox 11.36.0 is pushed on pypi

Cf. https://pypi.org/project/dropbox/

**Comment by greg-db** [comment]
Thanks for the note. That release has not been successfully added on PyPI. We'll follow up once we have an update.

**Comment by ghane** [comment]
Hi.  Is there an ETA for this?  Downstream packages are non-installable.

**Comment by imonkia** [comment]
Thanks for following up. Unfortunately, we still do not have any further updates regarding the release of v11.36.1 on PyPI.

**Comment by ghane** [comment]
> v11.36.2 is now published on PyPI.

Thank you!!!
