### ISSUE TITLE
is Python 3.9 supported? 

### ISSUE THREAD

**Issue by wilwet** [dropbox/dropbox-sdk-python#510]
I am using this on an Rpi and and pip does not auto upgrade. Is this due to that 3.9 does not seem to be supported.

**Comment by greg-db** [comment]
While it's not currently explicitly listed in the version list, the Dropbox Python SDK should work in Python 3.9, and appears to in my testing.

I'll be happy to help with any issues you're having with the Dropbox SDK, but I'd need some more information. If you still need help with this, please reply with:

- the steps to reproduce the issue, including relevant code snippet(s), but don't include any access or refresh token(s)
- the full text of any error or unexpected output

**Comment by wilwet** [comment]
Thank you, I don’t have any issues. Bit PIP did not upgrade to the latest version on the Rpi. I will wait for it to appear.

**Comment by greg-db** [comment]
Thanks for following up. The latest version of the Dropbox SDK is currently v12.0.2, which is posted both [to this repo itself](https://github.com/dropbox/dropbox-sdk-python/releases) as well as [on PyPI](https://pypi.org/project/dropbox/).

For reference, I tried installing an old version and then upgrading to the latest version using `pip3.9` to try this out, and it worked as expected for:
```
% pip3.9 install dropbox==11.0.0
<REDACTED FOR BREVITY>
Successfully installed dropbox-11.0.0

% pip3.9 install dropbox  --upgrade
<REDACTED FOR BREVITY>
Successfully installed dropbox-12.0.2
```

For help with `pip` itself, refer to the support resources for `pip`.
