### ISSUE TITLE
Improve sample updown.py

### ISSUE THREAD

**Issue by teopost** [dropbox/dropbox-sdk-python#55]
Please, add download sync to sample.

**Comment by greg-db** [comment]
Thanks! We'll consider this a feature request.

**Comment by Noe007** [comment]
we need a better version of this file

**Comment by jjssoftware** [comment]
Here's another vote for an improved version of this sample.

This implementation goes against what the documentation says about detecting changes with respect to using / not using client_modified as an indicator to determine if a file has changed or not: http://dropbox-sdk-python.readthedocs.io/en/master/moduledoc.html#dropbox.files.FileMetadata.

The offending line is here: https://github.com/dropbox/dropbox-sdk-python/blob/master/example/updown.py#L93

It's actually quite poor to document one thing as a rule then contradict that rule with sample code. I'd say this poor practice is really working around the fact that there's no file hash value present in the FileMetadata which could be reliably used to calculate change.

**Comment by greg-db** [comment]
Thanks for the additional feedback @jjssoftware !

**Comment by jjssoftware** [comment]
Continuing on with the discussion about requests for an improved version of the updown.py script, I've been working on a version [here](https://github.com/jjssoftware/asustor-dropbox) that now has a number of improvements and additional features including:

1. Improved exception handling
2. Multi-instancing / instance execution lock support
3. Logging
4. Download (full 2 way sync)

https://github.com/jjssoftware/asustor-dropbox/blob/master/bin/updown.py (https://github.com/jjssoftware/asustor-dropbox)
