### ISSUE TITLE
Support ID path format in delete/list_folder api?

### ISSUE THREAD

**Issue by andytzeng** [dropbox/dropbox-sdk-python#57]
Hi Team,

Some of the APIs can support ID path format. How about delete/list_folder API? It does not support currently. Is it possible to support it?

**Comment by greg-db** [comment]
This isn't currently possible, but we'll consider this a feature request. Thanks!

**Comment by greg-db** [comment]
The [`files_delete_v2`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_delete_v2) and [`files_list_folder`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.files_list_folder) methods now support passing in file IDs as `path`.
