### ISSUE TITLE
Size Error When Getting Image Thumbnail

### ISSUE THREAD

**Issue by ianrtracey** [dropbox/dropbox-sdk-python#58]
When getting the thumbnail using the following format:
`client.files_get_thumbnail(<path>)`
I receive the following response:
`(400, u'Error in call to API function "files/get_thumbnail": HTTP header "Dropbox-API-Arg": size: unknown tag \'s\'')`

**Comment by ianrtracey** [comment]
Also, when trying to create a ThumbnailSize object using:
`dropbox.files.ThumbnailSize('w128h128', None)`
I get:
`Invalid tag 'w128h128'`

**Comment by greg-db** [comment]
@ianrtracey it sounds like you may be on an old/beta version of the SDK. Please upgrade to the latest version and let me know if that does or doesn't help.
