### ISSUE TITLE
Dropbox emailed me that my Python Core SDK is out of date

### ISSUE THREAD

**Issue by akrherz** [dropbox/dropbox-sdk-python#59]
I just started using the master build of the dropbox-sdk found here and today I got this email from api-support@dropboxmail.com (with app name redacted)

```
We're writing to you because our logs indicate that you have at least one Dropbox API app (...) using an old version of the Python Core
SDK, with an out of date certificate file.

The Dropbox Python Core SDK implements certificate pinning, based on a list of certificates included in the SDK, in order to help secure the
connection to the Dropbox API servers.

On August 1st, 2016, the Dropbox API servers will be updated to use a new certificate, so you’ll need to update the version of the SDK used in your
app to match. The latest version of the Python Core SDK already contains the updated certificate file:

https://www.dropbox.com/l/xPCwR0s4CoICzox5c2OOxh?text=1[1]

You can refer to the CHANGELOG file included in the SDK for a list of changes.

Please update your app to use the latest SDK by 8/1/16 to ensure continued access to the Dropbox API.

Thanks!

- The Dropbox Platform Team
```

Is this some known current deficiency of this v2 preview SDK?  If nothing else, perhaps this ticket will help others that are puzzled/confused by this.  Thanks!

**Comment by greg-db** [comment]
Thanks for the report! If you're only using the latest version of the SDK from here, there's nothing extra you need to do. You likely just got the email because sometimes the version reporting is ambiguous, so the email campaign erred on the side of caution.

**Comment by akrherz** [comment]
OK! Thank you for the kind and quick response.  I am using the SDK from here.
