### ISSUE TITLE
Documentation bug: in files_upload(), mute is a bool, so it can't be u'true'

### ISSUE THREAD

**Issue by anishathalye** [dropbox/dropbox-sdk-python#6]
[This](http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.base.DropboxBase.files_upload) is a bit confusing:

<img width="538" alt="screen shot 2015-08-21 at 11 14 16 pm" src="https://cloud.githubusercontent.com/assets/3526486/9422815/63b82d28-485a-11e5-9c68-42f287b14b80.png">

mute is a bool, so it doesn't make sense to set it to u'true'.

**Comment by braincore** [comment]
Thanks for the tip! The latest SDK and documentation corrects this issue: http://dropbox-sdk-python.readthedocs.org/en/master/moduledoc.html#dropbox.base.DropboxBase.files_upload
