### ISSUE TITLE
out of date certificate file in SDK?

### ISSUE THREAD

**Issue by andytzeng** [dropbox/dropbox-sdk-python#60]
Hi Team,

I got the mail from api support of Dropbox as below:

> We're writing to you because our logs indicate that you have at least one Dropbox API app (Trend Micro Cloud Storage Scanner - dev, Trend Micro Cloud Storage Scanner α) using an old version of the Python Core SDK, with an out of date certificate file. 

>The Dropbox Python Core SDK implements certificate pinning, based on a list of certificates included in the SDK, in order to help secure the connection to the Dropbox API servers.

>On August 1st, 2016, the Dropbox API servers will be updated to use a new certificate, so you’ll need to update the version of the SDK used in your app to match. The latest version of the Python Core SDK already contains the updated certificate file:

>https://www.dropbox.com/developers-v1/core/sdks/python

However, the link points to v1-API whose certificate file (trusted-certs.crt) is the same as the one inside of v2 sdk.

So, should I care this notification or the trusted-certs.crt needs to be updated?

Thank you.

**Comment by greg-db** [comment]
If you're already using this v2 SDK, no further action is required. Thanks for checking!

**Comment by andytzeng** [comment]
Thank you for the confirming. :)
