### ISSUE TITLE
SDK incompatible with stock OS X 10.11 six module (Xcode, not Homebrew)

### ISSUE THREAD

**Issue by floatingatoll** [dropbox/dropbox-sdk-python#62]
Hi, using Xcode latest and OS X 10.11, I encountered this issue with the Dropbox SDK:

https://github.com/Eugeny/reconfigure/pull/17

The version of six provided with OS X does not include the PY2 constant, and so your SDK fails to operate correctly.

I encountered significant difficulty trying to upgrade the system-provided six, as System Protection prohibits alteration of the non-user-installed six library. I eventually worked around this issue with:

`sudo pip install --force-reinstall -I --no-cache-dir six`

Which instructed it to simply install the new version, with no regard for whether it was already installed or not.

But this entire issue would be repaired by simply not using the PY2 constant for the version check, as done at the pull request above. I propose this would improve your compatibility with OS X in general.

**Comment by braincore** [comment]
Just wondering, how did you install the library? We explicitly list a version of six that contains `PY2`. Does the installation not override the system six?

**Comment by rogebrd** [comment]
Closing due to outdated version and no fix
