### ISSUE TITLE
lost timezone

### ISSUE THREAD

**Issue by newbery** [dropbox/dropbox-sdk-python#64]
In `dropbox.babel_serializers.js`, it appears that the UTC/GMT timezone in the original datetime string is lost during the conversion of a `Timestamp` value to python object,
```python
    if isinstance(data_type, bv.Timestamp):
        try:
            return datetime.datetime.strptime(val, data_type.format)
        except ValueError as e:
            raise bv.ValidationError(e.args[0])
```

**Comment by braincore** [comment]
That's correct. The Dropbox server, however, only ever sends UTC timestamps.

**Comment by newbery** [comment]
Perhaps it might be helpful to add something in the documentation to warn users of this sdk that a naive datetime is returned and maybe some hint on how to reapply the UTC/GMT timezone to make it "aware" again?  The current documentation can easily mislead one into believing that you would be getting a timezone aware datetime.
