### ISSUE TITLE
files_upload not set client_modified property

### ISSUE THREAD

**Issue by aicpp** [dropbox/dropbox-sdk-python#67]
I wrote script to check this issue - https://gist.github.com/aicpp/dab6ab71065ce896b0e5d94060bc6109

When upload  first time - `client_modified` is set well.
If upload to exists dropbox file with mode `dropbox.files.WriteMode.overwrite`  parameter `client_modified` is not change.

**Comment by greg-db** [comment]
Are you uploading the same data each time? If the data doesn't change, Dropbox doesn't consider it a new version, so the metadata won't change.

**Comment by aicpp** [comment]
Thank you for reply. Yes, file itself is not change. Is there any way to get hash of file in Dropbox without download it?

**Comment by greg-db** [comment]
No, the Dropbox API doesn't return file hashes, but I'll be sure to pass this along as a feature request.

**Comment by greg-db** [comment]
The Dropbox API now offers a hash of file data that you can use to verify a file's contents. It isn't a single MD5 or SHA1, but rather a combination of SHA256 hashes of the pieces of the file. You can find it in the Python SDK as [`FileMetadata.content_hash`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.files.FileMetadata.content_hash).

You can find more information here:

https://www.dropbox.com/developers/reference/content-hash

**Comment by aicpp** [comment]
Thank you very much.
I excpect calculating hash using 4K blocks it's for performance reasons. For parallel processing.
