### ISSUE TITLE
Error in documentation: files_download_to_file returns only one argument, not two.

### ISSUE THREAD

**Issue by hq6** [dropbox/dropbox-sdk-python#70]
The [documentation](http://dropbox-sdk-python.readthedocs.io/en/master/moduledoc.html#dropbox.dropbox.Dropbox.files_download_to_file) for `files_download_to_file` claims that it returns the tuple `(dropbox.files.FileMetadata, requests.models.Response)`, but it returns only the first half of the tuple.

**Comment by navyad** [comment]
@braincore 
Should we make correction  in the doc specifying the return type as `dropbox.files.FileMetadata`
OR
Should we make correction in the code to return complete request object  consisting `(dropbox.files.FileMetadata, requests.models.Response)`

**Comment by braincore** [comment]
Yes, I've been meaning to get to this. That particular code is auto-generated by [Stone](https://github.com/dropbox/stone), which we also maintain. We'll need to rework the generator to produce the correct output type in the docstring.

**Comment by rogebrd** [comment]
Closing as this method has since been replaced by a combination of download and save_body_to_file methods

**Comment by rogebrd** [comment]
This references the `master` branch of readTheDocs.  We only support the `latest` and `stable` branches both of which has this issue fixed.
