### ISSUE TITLE
Why does DropboxOAuth2Flow still return user_id instead of account_id?

### ISSUE THREAD

**Issue by fniephaus** [dropbox/dropbox-sdk-python#75]
I understand that `uid` as used in API v1 is going to be deprecated and that we should use `account_id` in API v2 instead.
Why are `DropboxOAuth2Flow` and `DropboxOAuth2FlowNoRedirect` still [returning an old `user_id`](http://dropbox-sdk-python.readthedocs.io/en/master/moduledoc.html?#dropbox.oauth.DropboxOAuth2Flow.finish) instead of a new `account_id`?

**Comment by greg-db** [comment]
Thanks for pointing that out! That Python SDK OAuth flows haven't been updated to include that yet.

(As a workaround you can call [`users_get_current_account`](https://dropbox-sdk-python.readthedocs.io/en/master/moduledoc.html#dropbox.dropbox.Dropbox.users_get_current_account) to get it.)

**Comment by fniephaus** [comment]
That's exactly what I ended up doing. Could you update this when the issue has been resolved? Thanks

**Comment by greg-db** [comment]
Sure, we'll close this it's done.

**Comment by braincore** [comment]
This is fixed in 7.1.0. Note that the 7.x.x versions break compatibility with 6.x.x in two ways. One of the ways is that the result of the OAuth flow is now an object with an `account_id` field rather than a tuple.
