### ISSUE TITLE
Internal Server error when files_delete a folder which contains more than 10,000 files.

### ISSUE THREAD

**Issue by chunyenyeh** [dropbox/dropbox-sdk-python#80]
Hi team,

I receive InternalServerError after I call files_delete to delete a folder which contains more than 10,000 files.
In dropbox_v1 api, fileops/move will return "406 Too many files would be involved in the operation for it to complete successfully".
But now dropbox_v2 api files_delete returns "500 InternalServerError".
May dropbox server return the same erorr "too_many_files" as files_copy and files_move?

Here is the traceback.

```
  File "/python/dropbox/base.py", line 308, in files_delete
    None,
  File "/python/dropbox/dropbox.py", line 249, in request
    timeout=timeout)
  File "/python/dropbox/dropbox.py", line 341, in request_json_string_with_retry
    timeout=timeout)
  File "/python/dropbox/dropbox.py", line 430, in request_json_string
    raise InternalServerError(request_id, r.status_code, r.text)
Oct 24
```

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by braincore** [comment]
@chunyenyeh: Have you tried our new `delete_batch` endpoint that has an asynchronous interface? https://www.dropbox.com/developers/documentation/http/documentation#files-delete_batch

**Comment by braincore** [comment]
Here are the Python docs for the delete batch endpoint: http://dropbox-sdk-python.readthedocs.io/en/master/moduledoc.html#dropbox.dropbox.Dropbox.files_delete_batch

**Comment by greg-db** [comment]
Apologies for the delay following up on this. This was updated to properly return a `too_many_files` error.
