### ISSUE TITLE
How renaming is happening?

### ISSUE THREAD

**Issue by anandthati** [dropbox/dropbox-sdk-python#81]
Hi,
I have gone through the file.py and found autorename function.
Is this function used to rename files and sync?

In general, If we rename a file in the dropbox folder it should create a new file in the dropbox web-app and it will sync the same file.
Example: test.txt is there in the dropbox web as well as in the dropbox folder. When I rename test.txt file to hello.txt in dropbox folder. In OS when rename a file it will delete old file and create new file. 
This hello.txt will sync to dropbox web and also test.txt is already present in the dropbox web so again it will  sync to dropbox folder. 
Why this it is not syncing old file to dropbox folder??

Thanks in advance.

**Comment by greg-db** [comment]
@anandthati I'm not sure I follow. Can you share the code you're using that's giving you trouble? Also, please be sure to include the unexpected output, whether that's a result from the API or screenshots of Dropbox. Thanks in advance! 

Alternatively, if this is about syncing issues with your Dropbox account in general, you can contact support here:

https://www.dropbox.com/support

(This GitHub issues page is just for using the Python SDK.)

**Comment by Jufik** [comment]
@anandthati I don't know for renaming, but when using "move", you'll get a relocation response.
Be carefull though, if you use the webhook, you will get 2 entries in files_list_folder: the first one deletes your file, the second one re-create it.... that is a mess when you try to keep sync of your folders......

**Comment by rogebrd** [comment]
Closing due to stale issue with no follow up from reporter.
