### ISSUE TITLE
Python Requests Forces Latin1 Headers, Dropbox allows UTF-8 Filenames

### ISSUE THREAD

**Issue by ianzimmerman** [dropbox/dropbox-sdk-python#82]
Trying to download a file from user's dropbox via python API v2:

        headers = {
            'Authorization': 'Bearer {}'.format(token),
            'Dropbox-API-Arg': '{{"path": "{}"}}'.format(item.location)
        }

        url = "https://content.dropboxapi.com/2/files/download"

        r = requests.post(url, headers=headers)

Results in error for path '/xxx/yyy/FallWinter 4.20.16-2.pdf' (returned from Dropbox API):

    File "/Users/i/.pyenv/versions/3.5.2/lib/python3.5/http/server.py", line 512, in send_header ("%s: %s\r\n" % (keyword, value)).encode('latin-1', 'strict'))
    UnicodeEncodeError: 'latin-1' codec can't encode character '\uf022' in position 73: ordinal not in range(256)

Via requests issue: https://github.com/kennethreitz/requests/issues/1926, headers MUST be latin1

Am I correct in understanding then, that it is unsupported to get UTF-8 filenames from python API via requests? Can the file path be included in body of post rather than header?

See also: https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.request

**Comment by ianzimmerman** [comment]
As a workaround, using the file ID as the path will work in this case. '{{"path": "id:XXXXXXXXXXXX"}}'

**Comment by greg-db** [comment]
That error isn't coming from the Dropbox API itself, but rather seems to be a local encoding issue/

You can download files with UTF-8 filenames from the API, but the characters do need to be properly escaped. I believe you can use `json.dumps` to do this for you, since you're not using the Dropbox SDK.

For your provided code, that would look something like this instead:
```
        'Dropbox-API-Arg': json.dumps({"path": item.location})
```

Does that work for you?

**Comment by ianzimmerman** [comment]
@greg-db perfect, thanks. I did switch to using id in the end as it may prevent other issues.

Thank you!

**Comment by cakoose** [comment]
@ianzimmerman: I just wanted to make sure that you're now always using the `json.dump` pattern Greg provided.  Raw Python string interpolation will get you into encoding trouble eventually.

**Comment by ianzimmerman** [comment]
@cakoose thanks! I'll keep that in mind.
