### ISSUE TITLE
Improve regex for path matching

### ISSUE THREAD

**Issue by althonos** [dropbox/dropbox-sdk-python#84]
Hi there !

Just tested that, in its current form, the regex that checks the file path excludes "/" and "." (when you try ```dbx.files_list_folder('/')``` or ```dbx.files_list_folder('.')``` for instance), but it doesn't protect the Dropbox server from a malformed query of the form: ```dbx.files_list_folder('/.')```. In fact, any path ending with ```"/."``` will be sent to Dropbox without issue, only to raise an `InternalServerError` afterwards.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by braincore** [comment]
Thanks for the note. This is a known issue, and not one we're really looking to fix. The regex isn't meant as a comprehensive validation (the server has more complex logic for this), but simply as a sanity check to catch and report basic mistakes like `/` for root and a path without a `/` prefix.
