### ISSUE TITLE
Dropbox Paper support : create doc

### ISSUE THREAD

**Issue by foxmask** [dropbox/dropbox-sdk-python#87]
Hi,

any chance to support [Dropbox Paper API](https://www.dropbox.com/developers/documentation/http/documentation#paper) ?

regards

**Comment by greg-db** [comment]
Yes, those endpoints should be available in the SDK the next time we rebuild it.

**Comment by foxmask** [comment]
Hi,

I just discovered that [there is no way to create doc](https://www.dropboxforum.com/t5/API-support/Paper-API-Create-Paper-Document/m-p/200017#M9348) - it's very very annoying :( 

I planned to migrate from Evernote but here i'm facing a wall

**Comment by greg-db** [comment]
That's correct, the API currently doesn't offer a way to create documents. I'll add your vote to the feature request.

**Comment by foxmask** [comment]
Thanks !
I waited for paper since a long time 😊

**Comment by greg-db** [comment]
@foxmask The Paper methods are available in the SDK now (though there's still no way to create docs). You can find the documentation here:

https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.paper_docs_archive

**Comment by foxmask** [comment]
Hi
I m sorry but I dont see , with this method, how i could create a paper note, may be the doc is not complet ?

**Comment by maxking** [comment]
@foxmask You can't create docs as of now through the API. @greg-db corrent me if I am wrong, but the update only brings the parts that are already working in the API(read access to docs) to this python-sdk.

**Comment by greg-db** [comment]
That's correct, the API and SDK currently don't offer a way to create Paper docs. This SDK update just adds the functionality that has been added to the API, such as reading docs, etc.

**Comment by techpines** [comment]
@greg-db I'm interested in this feature as well.  Do you know the best way to get updates on when features are added to the Dropbox API?

**Comment by foxmask** [comment]
We could be, If the issue could stay opened until that feature be done

**Comment by greg-db** [comment]
I've re-opened this issue and will follow up here if/when creating a Paper document via the API available.

**Comment by Raymond26** [comment]
+1 for creating Paper documents via API

**Comment by greg-db** [comment]
Creating and updating Paper documents is now possible via [`paper_docs_create`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.paper_docs_create) and [`paper_docs_update`](https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html#dropbox.dropbox.Dropbox.paper_docs_update) respectively.

**Comment by foxmask** [comment]
Any example on how to use it ? 
I mean, once we did 
```
>>> import dropbox
>>> dbx = dropbox.Dropbox("YOUR_ACCESS_TOKEN")
```

how to continue with 

```
import dropbox
from dropbox.base import DropboxBase
from dropbox.exceptions import ApiError
from dropbox.paper import ImportFormat, PaperDocCreateError

content = b"<h1>My title</h1><p>my content</p>"
dbx_base = DropboxBase()
try:
    r = dbx_base.paper_docs_create(content, ImportFormat('html'))
    print(r)
except PaperDocCreateError as e:
    print("PaperDocCreateError ERROR %s" % e)
except ApiError as e:
    print("API ERROR %s" % e)
```

This return `None` and I dont see the doc on my dropbox account.

**Comment by greg-db** [comment]
@foxmask You shouldn't use `DropboxBase` directly. Your first snippet is the right way to build a client. The rest of your code otherwise looks fine, so it would be something like:

```
import dropbox
from dropbox.exceptions import ApiError
from dropbox.paper import ImportFormat, PaperDocCreateError

content = b"<h1>My title</h1><p>my content</p>"
dbx = dropbox.Dropbox("YOUR_ACCESS_TOKEN")

try:
    r = dbx.paper_docs_create(content, ImportFormat('html'))
    print(r)
except PaperDocCreateError as e:
    print("PaperDocCreateError ERROR %s" % e)
except ApiError as e:
    print("API ERROR %s" % e)
```

**Comment by foxmask** [comment]
Thank you ! It's perfect now !
