### ISSUE TITLE
How to read a file inside the dropbox folder using python dropbox api V2?

### ISSUE THREAD

**Issue by mfarook** [dropbox/dropbox-sdk-python#89]
i need to know how files inside a dropbox folder can be read. For ex: if there are text and csv files inside a dropbox folder, then i need to read the contents of those file using python dropbox api V2?

**Comment by posita** [comment]
Hi @mfarook. Thanks for the question. The issues for this repository should be bug reports or feature requests for Dropbox's Python SDK.

If you'd like to learn how to use our APIs and SDKs, please take a look at the following resources available via the [developers section of Dropbox's website](https://www.dropbox.com/developers):

- [Dropbox Python SDK with examples](https://www.dropbox.com/developers/documentation/python) and [accompanying docs](http://dropbox-sdk-python.readthedocs.io/en/master/)
- [Dropbox general API endpoint documentation](https://www.dropbox.com/developers/documentation/http/documentation)
  - [`/2/files/download` endpoint documentation](https://www.dropbox.com/developers/documentation/http/documentation#files-download)
  - [`/2/files/list_folder` endpoint documentation](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) _et seq._

See also:

- [Dropbox Python SDK tutorial](https://github.com/posita/dropbox-api-primer) and [accompanying docs](https://dropbox-api-primer.readthedocs.io/en/master/tutorial.html)

**Comment by greg-db** [comment]
Also, for reference, the examples use the Python SDK `file_download` methods here:

- https://github.com/dropbox/dropbox-sdk-python/blob/master/example/updown.py#L158
- https://github.com/dropbox/dropbox-sdk-python/blob/master/example/back-up-and-restore/backup-and-restore-example.py#L55

**Comment by posita** [comment]
@mfarook, the [developer support area](https://www.dropbox.com/developers/support) may be useful to you as well.
