### ISSUE TITLE
Passing in Flask's request.args into DropboxOAuth2Flow's finish raises CsrfException

### ISSUE THREAD

**Issue by leerobert** [dropbox/dropbox-sdk-python#9]
Flask's request.args seems to return a MultiDict with the state and code params as strings. 

An example request.args: 

    ImmutableMultiDict([('code', 'YTUikDoXcTAAAAAAAAAAHXP77TSxxgsDq4feLLcqAFo'), ('state', "b'AS3w7Msx1ogjdQF30rRVyA=='")])

This results in a comparison of the stored session's CSRF to fail in comparison to the returned state's CSRF as a byte value is being compared to a string value:

    dropbox.client.CsrfException: expected b'04z6aywDB0ynAlvU42NJyQ==', got "b'04z6aywDB0ynAlvU42NJyQ=='"

I was able to get around this by writing my own utility function but I was just wanted to perhaps put the issue out there so others don't have to slog through SDK debugging.

**Comment by leerobert** [comment]
I think the issue lies in the fact base64 returns a regular string in python2 and a byte string for python3. I'm using python3 so the issue came up then. I'm gonna try out a quick fix and commit relevant code.

**Comment by braincore** [comment]
Thanks for the report! We've committed a fix in SDK version 3.27 available on PyPI. We appreciate the helpful pull request. We aren't directly merging them just because our build and release process is done primarily outside of this GitHub repository (think of this as a read-only copy of our SDK).
